### ISSUE TITLE
关于inter网卡连接2.4g/5g的wifi问题

### ISSUE THREAD

**Issue by Zhushixuan** [kirainmoe/hasee-tongfang-macos#100]
您好，首先谢谢您的团队提供tongfang这么好的一个软件，供我们一个体验mac系统。
电脑型号：z7m-kp7gc
系统：bigsur
问题描述：
第一种情况：使用tongfang自带的的airportltlwm是可以连接wifi的5g频段的，但是2.4g不可连接。一直是让输入密码。
第二种情况：在升级airportltlwm2.0以后，无法连接5g频段，会显示无ip地址后，会断掉，然后继续显示无ip地址，一直循环，但是可以连接2.4g频段，不过网络也不是很通畅。
希望可以看到这个问题反馈。

**Comment by Zhushixuan** [comment]
![Uploading 59A59C6C-DA94-411C-A73E-5B7E30E59DE0.png…]()

**Comment by kirainmoe** [comment]
Intel 网卡驱动相关问题请反馈到 https://github.com/OpenIntelWireless/itlwm 项目。

请先尝试升级到最新版 itlwm / AirportItlwm (2.1.0): https://github.com/OpenIntelWireless/itlwm/releases

并请同时阅读：
- [itlwm 常见问题](https://docs.oiw.workers.dev/itlwm/FAQ.html)
- [itlwm 问题解决](https://docs.oiw.workers.dev/itlwm/Troubleshooting.html)
