### ISSUE TITLE
触摸板双击左上角屏蔽触摸板功能

### ISSUE THREAD

**Issue by 7workday** [kirainmoe/hasee-tongfang-macos#105]
<img width="825" alt="截屏2022-07-18 22 28 49" src="https://user-images.githubusercontent.com/56962992/179534666-bfe830b2-7db0-41b9-b886-081cf590da5f.png">
大佬，内核加载如图，在10.14版本中有双击触摸板左上角屏蔽触摸板功能，升级到12.4后双击不能屏蔽

**Comment by kirainmoe** [comment]
使用 22.6.15 以上版本，重新使用 Utility 安装增强工具。

**Comment by 7workday** [comment]
‘使用 22.6.15 以上版本’，上句22.6.15版本是什么软件？
tongfang-utility上安装增强功能守护程序重新安装不起作用，fn快捷键除了fn+f5不起作用其他都有用，包括fn+f1

**Comment by 7workday** [comment]
大佬，‘使用 22.6.15 以上版本’，上句22.6.15版本是什么软件？
tongfang-utility上安装增强功能守护程序重新安装不起作用，fn快捷键除了fn+f5不起作用其他都有用，包括fn+f1
