### ISSUE TITLE
Monterey 系统连接Airpods时无法播放在线音乐，无限切换下一曲

### ISSUE THREAD

**Issue by KyleChoy** [kirainmoe/hasee-tongfang-macos#107]
设备：Z7M-CT7GS
系统：12.4
EFI：22.7.17
情况描述：

- 使用扬声器时，Apple Music正常播放在线音乐
- 连接AirPods Pro时，其他软件正常播放，Apple Music只能播放已下载的音乐，在线播放会无限地切歌（没有开无损和杜比）

网上搜索的方案是针对有独显的黑苹果进行的，似乎和DRM有关，不知道作者能否在本项目中解决此问题。

**Comment by kirainmoe** [comment]
根据 https://dortania.github.io/OpenCore-Post-Install/universal/drm.html#fixing-drm 中的说法，纯核显机型在 macOS 10.12.3 之后无法解 DRM，目前似乎没有解决方案。
