### ISSUE TITLE
机型反馈

### ISSUE THREAD

**Issue by hashiqi12138** [kirainmoe/hasee-tongfang-macos#108]
## 机型：
神舟 z7m-kp5dc

## efi机型：
神舟 z7m-kp5gc

## 配置详情
![image](https://user-images.githubusercontent.com/52161363/182005686-fadc6bae-0f49-4174-9f94-6d2b73e86fc3.png)

## 功能情况：

网卡，蓝牙正常

usb 需要定制，定制后正常

同方助手的 风扇貌似控制无效

其他功能正常，正常使用无问题

kerna task cpu 占用有时较高

nvdia 无法驱动（暂时无解）

**Comment by kirainmoe** [comment]
KP5DC 是蓝天模具，同方机型的 EFI 无法完全兼容，为同方模具适配的风扇控制在蓝天模具上无效，蓝天机型风扇控制需找 ClevoControl. USB 和电池状态等也需要自行处理。

kernel_task 占用过高在电池损耗严重（系统提示需维修）或温度较高时会发生系统通过提高 kernel_task 的 CPU 占用减少用户程序 CPU 占用的情况。

**Comment by hashiqi12138** [comment]
感谢大佬回复
