### ISSUE TITLE
进入OpenCore前出现hda open pci i/o protocol (try disconnect hda quirk ) - already started

### ISSUE THREAD

**Issue by KyleChoy** [kirainmoe/hasee-tongfang-macos#109]
设备：Z7M-CT7GS
系统：12.6
EFI：22.7.17
情况描述：
- 进入OpenCore前出现黑屏，左上角出现hda open pci i/o protocol (try disconnect hda quirk ) - already started，等待几秒后进入opencore引导界面
- 打开UEFI- Audio里面的disconnect hda，问题仍在
- 直接关闭UEFI的驱动 AudioDxe.efi，问题解决

PS. 尝试清除过nvram，但没有效果

**Comment by KyleChoy** [comment]
补充：更新 OpenCore 0.8.4 的 AudioDxe.efi 可以修复。

**Comment by Justice1211** [comment]
求一份efi，谢谢

**Comment by KyleChoy** [comment]
> 求一份efi，谢谢

我发了一份pull request，你可以等作者合并或者直接下载：https://cowtransfer.com/s/0a472988d8b14c 

参考作者的教程在同方助手中使用：https://kirainmoe.feishu.cn/wiki/wikcnQ2ZtprTLOIKH2Zuij8lkkc

**Comment by Justice1211** [comment]
> > 求一份efi，谢谢
> 
> 我发了一份pull request，你可以等作者合并或者直接下载：https://cowtransfer.com/s/0a472988d8b14c 
> 
> 参考作者的教程在同方助手中使用：https://kirainmoe.feishu.cn/wiki/wikcnQ2ZtprTLOIKH2Zuij8lkkc

谢谢您

**Comment by Justice1211** [comment]
但是挺有趣的，咱们型号一样，我这个直接卡40%左右
