### ISSUE TITLE
设备关机断电后，插入电源线不进行任何操作会导致设备半开机

### ISSUE THREAD

**Issue by zxkmm** [kirainmoe/hasee-tongfang-macos#111]
设备关机断电后，插入电源线不进行任何操作会导致设备半开机，半开机表现为屏幕不亮，但是硬盘都在工作，键盘灯点亮。
此状态下如果按电源键开机，风扇会开始转动，但是转动约40秒后设备自动关机。此时再次按电源键可顺利开机，一切正常。
如果在设备断电且不插入电源线的情况下，用电源按钮开机，也会出现半开机现象。
所以无论是否插电源线，每次开机都会走一次“半开机”这个流程，较为影响使用。
环境均为最新版，同方unity中的核显固件和睡眠设置等各个选项都尝试修改过，都不起作用。
型号为z7mkp7gz。
提前感谢各位大佬给出任何建议！

**Comment by kirainmoe** [comment]
cmos 电池没电了吧

**Comment by zxkmm** [comment]
谢谢大佬指教！确实是电池没电了，我明天换一个电池。再次感谢！
