### ISSUE TITLE
开启蓝牙之后无法关闭

### ISSUE THREAD

**Issue by 0x112** [kirainmoe/hasee-tongfang-macos#21]
版本号：Mojave 10.14.5

**Comment by kirainmoe** [comment]
因为 Intel 的蓝牙设备不兼容 macOS 默认的蓝牙驱动，所以默认蓝牙无法关闭，你可以替换 /System/Library/Extensions 下的 IOBluetoothFamily.kext：https://www.lanzous.com/i4as08f

当然，蓝牙能不能关并没有什么影响。

**Comment by 0x112** [comment]
好的，看来只能按照wiki里的教程换掉网卡了。

想换成BCM94360CS2这个网卡，刚查了一下资料，发现这个网卡是2013年推出的，自带Intel AC9462是2017年推出的。性能和功耗方面差距是不是比较大？有BCM94360CS2和AC9462各方面参数的对比吗？

我macOS不是很常用，不知道替换成BCM94360CS2值不值...

**Comment by 0x112** [comment]
还有BCM94360CS2这个卡比较旧了，在未来的macOS版本会不会有可能不支持？

**Comment by kirainmoe** [comment]
功耗不清楚。性能的话因为 BCM94360CS2 是蓝牙 4.0，AC9462 是蓝牙 5.0，在蓝牙性能和兼容性上有一定的差距。但考虑到其它支持黑苹果的网卡也都是蓝牙 4.0/4.1 的水平，BCM94360CS2 还是可以选择的，如果你不是那么关心蓝牙的性能，此外 2.4G 可能会和蓝牙产生干扰。至于 WiFi 的速度我个人感觉没有什么区别，AC9462 本身也不是什么好卡。

未来的版本不知道，但就目前看来苹果仍然在使用 Broadcom 的网卡，在未来的一两个新版本内应该不会删除相关的驱动。

**Comment by 0x112** [comment]
嗯，看来想要完美只能换 DW1830 (BCM943602) 或 DW1560 (BCM94352Z) 了，那如果换了 DW1830 和 DW1560，也需要加上 Alternative Kexts 里面的这三个驱动吗？
```
Alternative Kexts/AirportBrcmFixup.kext
Alternative Kexts/BrcmFirmwareRepo.kext
Alternative Kexts/BrcmPatchRAM2.kext
```

**Comment by kirainmoe** [comment]
要。
