### ISSUE TITLE
10.15 beta版EFI的能运行在Mojave上面吗？

### ISSUE THREAD

**Issue by 0x112** [kirainmoe/hasee-tongfang-macos#22]
请问从这个版本开始 https://github.com/kirainmoe/hasee-tongfang-macos/commit/62a81d42aa0d4332ce1e982a661c20fbf4aef2c3 能不能运行在Mojave上？

**Comment by kirainmoe** [comment]
当然可以。

**Comment by 0x112** [comment]
好的，十分感谢
