### ISSUE TITLE
请问一下z7m-kp7sc可以使用安装吗？

### ISSUE THREAD

**Issue by iquanzhan** [kirainmoe/hasee-tongfang-macos#23]
下面是我的电脑配置：

处理器(CPU) | 英特尔 Core i7-8750H @ 2.20GHz 六核 |   |  
-- | -- | -- | --
主	板 | Notebook N8xEJEK |   |  
内	存 | 16 GB ( 金士顿 DDR4 2666MHz / 镁光 DDR4 2666MHz ) |   |  
硬	盘 | Phison SATA SSD ( 256 GB / 固态硬盘 ) |   |  
显	卡 | Nvidia GeForce GTX 1050 Ti ( 4 GB ) |   |  
显示器 | NCP001C LM156LF1L03 ( 15.5 英寸 )

**Comment by kirainmoe** [comment]
> 注意，蓝天模具的神舟 Z7-KP7SC, Z7-KP7S1、同方模具的七代平台机型 Z7-KP7GT, Z7-KP7D2 等不属于该系列，并不保证能完全兼容，这些机型也不是本仓库配置文件的目标机型，因此针对此类设备的兼容性问题，请您自行解决。
