### ISSUE TITLE
神舟 z7-KP7EC 更新后触摸板无法使用

### ISSUE THREAD

**Issue by liucg1995** [kirainmoe/hasee-tongfang-macos#24]
更新后触摸板无法使用

**Comment by kirainmoe** [comment]
> Q: 为什么更新到新版本之后，触摸板等功能失效了？
A: 请使用以下命令重建 kext 缓存并重启电脑：
```
sudo kextcache -i /
```

**Comment by liucg1995** [comment]
> > Q: 为什么更新到新版本之后，触摸板等功能失效了？
> > A: 请使用以下命令重建 kext 缓存并重启电脑：
> 
> ```
> sudo kextcache -i /
> ```

执行过不管用
我的电脑是  KP7EC    触摸板的原因？？？

**Comment by liucg1995** [comment]
> > Q: 为什么更新到新版本之后，触摸板等功能失效了？
> > A: 请使用以下命令重建 kext 缓存并重启电脑：
> 
> ```
> sudo kextcache -i /
> ```

执行过不管用
我的触摸板没有触摸手势

**Comment by kirainmoe** [comment]
1. 检查电池是否正常显示
2. 使用 kextstat | grep Voodoo 检查VoodooI2C，VoodooI2CHID，VoodooGPIO是否正常加载。
3. 确认你使用了正确机型的 config

**Comment by liucg1995** [comment]
机型下载的没错
驱动只显示两个
没有2CHID




 
---原始邮件---
发件人: "Yume Maruyama"<notifications@github.com>
发送时间: 2019年6月22日(星期六) 下午5:44
收件人: "kirainmoe/hasee-tongfang-macos"<hasee-tongfang-macos@noreply.github.com>;
抄送: "liucg"<164445438@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [kirainmoe/hasee-tongfang-macos] 神舟 z7-KP7EC 更新后触摸板无法使用 (#24)


 
检查电池是否正常显示 

使用 kextstat | grep Voodoo 检查VoodooI2C，VoodooI2CHID，VoodooGPIO是否正常加载。 

确认你使用了正确机型的 config

**Comment by kirainmoe** [comment]
请贴上 sudo kextcache -i /的输出
