### ISSUE TITLE
无法记住上一次选择的分区系统

### ISSUE THREAD

**Issue by selfgrowth** [kirainmoe/hasee-tongfang-macos#26]
clover每次默认都是从mac系统启动，但是我的config.plist里面已经设置DefaultVolume为LastBootedVolume了，还是不能从上次选择的分区启动，尝试过将EmuVariableUefi-64.efi删除，这样下来clover可以默认启动上一次的系统，但是Mac系统这边重启，关机等功能会卡死导致死机

**Comment by kirainmoe** [comment]
目前已知是 Clover 和 NVRAM 方面的问题，引导 Windows 不会更新 NVRAM 中的 lastBootedVolume，暂时没有找到解决方案。

**Comment by selfgrowth** [comment]
`引导 Mac 会更新 NVRAM 中的 lastBootedVolume`意思是引导mac时修改了nvram.plist文件中的某一个字段来记录上次启动分区是吗? 如果是这样的话,我在启动windows之后能不能手动修改nvram.plist来达到目的?

**Comment by Rarstar** [comment]
不知道怎么引起的，但是删除了EmuVariableUefi-64.efi后可以记住了

**Comment by kirainmoe** [comment]
Fixed in 7c8a0ba. Please upgrade to the latest version of config.
