### ISSUE TITLE
Support for TongFang GI5CN5E i7-8750h+uhd630

### ISSUE THREAD

**Issue by rodgomesc** [kirainmoe/hasee-tongfang-macos#27]
Hello Guys, first, thanks for this wonderfull project, and sorry for my english

iam a very old linux user and a new fan boy of hackintosh,

After i folow the instructions in README, iam stuck on loading scren above;

**
![image](https://user-images.githubusercontent.com/4893591/61176953-3ab80680-a5a0-11e9-80a4-ae3b1b05431d.png)
**

in the config.plist of this repository has a lot of information and I can not distinguish which information is related to the operation of the uhd 630, Would you help me?

i can boot sucessfull with this [config.plist](https://gist.github.com/rodgomesc/cdf01ee75f0651eaab50b142f5943440), but no hardware aceleration and only show 7mb of video

my hardware is:

```bash
00:00.0 Host bridge: Intel Corporation 8th Gen Core Processor Host Bridge/DRAM Registers (rev 07)
00:01.0 PCI bridge: Intel Corporation Xeon E3-1200 v5/E3-1500 v5/6th Gen Core Processor PCIe Controller (x16) (rev 07)
00:02.0 VGA compatible controller: Intel Corporation UHD Graphics 630 (Mobile)
00:08.0 System peripheral: Intel Corporation Xeon E3-1200 v5/v6 / E3-1500 v5 / 6th/7th Gen Core Processor Gaussian Mixture Model
00:12.0 Signal processing controller: Intel Corporation Cannon Lake PCH Thermal Controller (rev 10)
00:14.0 USB controller: Intel Corporation Cannon Lake PCH USB 3.1 xHCI Host Controller (rev 10)
00:14.2 RAM memory: Intel Corporation Cannon Lake PCH Shared SRAM (rev 10)
00:15.0 Serial bus controller [0c80]: Intel Corporation Cannon Lake PCH Serial IO I2C Controller #0 (rev 10)
00:16.0 Communication controller: Intel Corporation Cannon Lake PCH HECI Controller (rev 10)
00:17.0 SATA controller: Intel Corporation Cannon Lake Mobile PCH SATA AHCI Controller (rev 10)
00:1b.0 PCI bridge: Intel Corporation Cannon Lake PCH PCI Express Root Port #17 (rev f0)
00:1b.4 PCI bridge: Intel Corporation Cannon Lake PCH PCI Express Root Port #21 (rev f0)
00:1d.0 PCI bridge: Intel Corporation Cannon Lake PCH PCI Express Root Port #14 (rev f0)
00:1d.6 PCI bridge: Intel Corporation Cannon Lake PCH PCI Express Root Port #15 (rev f0)
00:1e.0 Communication controller: Intel Corporation Device a328 (rev 10)
00:1f.0 ISA bridge: Intel Corporation Device a30d (rev 10)
00:1f.3 Audio device: Intel Corporation Cannon Lake PCH cAVS (rev 10)
00:1f.4 SMBus: Intel Corporation Cannon Lake PCH SMBus Controller (rev 10)
00:1f.5 Serial bus controller [0c80]: Intel Corporation Cannon Lake PCH SPI Controller (rev 10)
01:00.0 VGA compatible controller: NVIDIA Corporation GP107M [GeForce GTX 1050 Ti Mobile] (rev a1)
01:00.1 Audio device: NVIDIA Corporation GP107GL High Definition Audio Controller (rev a1)
04:00.0 Network controller: Qualcomm Atheros QCA9565 / AR9565 Wireless Network Adapter (rev 01)
05:00.0 Unassigned class [ff00]: Realtek Semiconductor Co., Ltd. RTL8411B PCI Express Card Reader (rev 01)
05:00.1 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller (rev 12)
```
with: 

* i7-8750h - i can't make uhd630 working, how can i adapt this config.plist  to solve?
*  ALC269VC v3 - Working with layout 8 in AppleALC
* Wireless - Working with AR9565 Wireless Network Adapter

**Comment by kirainmoe** [comment]
Please boot with verbose mode and post a screenshot when you stuck on somewhere. You can use `-v` bootflag or press Space on Clover and check `verbose`.

Tongfang GI5CN5E model is likely to be `kp7gc` model.

**Comment by rodgomesc** [comment]
> Please boot with verbose mode and post a screenshot when you stuck on somewhere. You can use -v bootflag or press Space on Clover and check verbose. BTW, which version of macOS you are running?

Iam using `Mojave 14.5`, i folow your instructions using your project and used `-v` flag and above, here is the output

[Stuck screen](https://pasteboard.co/InWq6nb.jpg)

> In the config.plist you provide, you have set FakeID --> IntelGFX to 0x12345678, Graphics --> ig-platform-id to 0x591B0000 (this platform-id is for Kaby Lake HD630). Make sure your Lilu.kext and WhateverGreen.kext are the latest version, and set FakeID --> IntelGFX to empty, Graphics --> ig-platform-id to 0x3e9b0000 (this is for mobile CoffeeLake UHD630) or empty, then it should work. You may meet 3 mins blackscreen on boot, this problem can be easily solved.

Using this recomendation on my config.plist system reboots when progress bar is around 40%

**Comment by kirainmoe** [comment]
Your screenshot shows that a kernel panic occurred, but as `lilu.kext` outputs too much garbage info, I can't clearly figure out the reason, so I need to know what is the panic related, can you try to boot with flag `-v -liluoff` and tell me if you can boot to the system with no graphics acceleration or get other error message? Deleting `Alternative Kexts` folder doesn't matter.

---- 

In case of automatic reboot, you can boot with flag `-v debug=0x1000 keepsyms=1`.

**Comment by rodgomesc** [comment]
Using `-v -liluoff` the panic screen are the same

**Comment by rodgomesc** [comment]
So, lets Begin from the beginning, i start copying all kext to /other folder, and iam stuck on this screen

![15631309886051498761386861000102](https://user-images.githubusercontent.com/4893591/61188122-05b7bc80-a651-11e9-8148-0844cee335b0.jpg)

**Comment by rodgomesc** [comment]
So, I searched the entire system behind a startup log, but I did not find it, so I decided to record using the cell phone and send it to youtube, it is possible to see the error when pausing the video, I am also leaving attached the exact moment when the error occurs, I hope it helps

**Comment by kirainmoe** [comment]
I guess that the problem may be caused by DVMT pre-allocated memory or built-in display (if you have a 4k built-in displayer). Can you boot to Windows or Linux（or if you can set DVMT in BIOS）and see the size of DVMT pre-allocated memory? It should be 64MB or larger.

**Comment by rodgomesc** [comment]
1 - iam using 1080p display of the laptop4
2 - my bios not have a option to change DVMT
3 - this info helps?
```
❯ lshw -c display
WARNING: you should run this program as super-user.
  *-display                 
       description: VGA compatible controller
       product: GP107M [GeForce GTX 1050 Ti Mobile]
       vendor: NVIDIA Corporation
       physical id: 0
       bus info: pci@0000:01:00.0
       version: a1
       width: 64 bits
       clock: 33MHz
       capabilities: vga_controller bus_master cap_list rom
       configuration: driver=nvidia latency=0
       resources: irq:135 memory:a5000000-a5ffffff memory:90000000-9fffffff memory:a0000000-a1ffffff ioport:6000(size=128) memory:a6000000-a607ffff
  *-display
       description: VGA compatible controller
       product: UHD Graphics 630 (Mobile)
       vendor: Intel Corporation
       physical id: 2
       bus info: pci@0000:00:02.0
       version: 00
       width: 64 bits
       clock: 33MHz
       capabilities: vga_controller bus_master cap_list rom
       configuration: driver=i915 latency=0
       resources: irq:130 memory:a4000000-a4ffffff memory:80000000-8fffffff ioport:7000(size=64) memory:c0000-dffff
WARNING: output may be incomplete or inaccurate, you should run this program as super-user.
```

5 - buildin display info:

```
❯ cat /sys/class/drm/card0-eDP-1/edid | edid-decode
Extracted contents:
header:          00 ff ff ff ff ff ff 00
serial number:   06 af ed 61 00 00 00 00 00 1a
version:         01 04
basic params:    95 22 13 78 02
chroma info:     59 25 93 58 59 93 29 26 50 54
established:     00 00 00
standard:        01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01
descriptor 1:    78 37 80 b4 70 38 2e 40 6c 30 aa 00 58 c1 10 00 00 18
descriptor 2:    00 00 00 0f 00 00 00 00 00 00 00 00 00 00 00 00 00 20
descriptor 3:    00 00 00 fe 00 41 55 4f 0a 20 20 20 20 20 20 20 20 20
descriptor 4:    00 00 00 fe 00 42 31 35 36 48 41 4e 30 36 2e 31 20 0a
extensions:      00
checksum:        ea

EDID version: 1.4
Manufacturer: AUO Model 61ed Serial Number 0
Made in year 2016
Digital display
6 bits per primary color channel
DisplayPort interface
Maximum image size: 34 cm x 19 cm
Gamma: 2.20
Supported color formats: RGB 4:4:4
First detailed timing includes the native pixel format and preferred refresh rate
Display x,y Chromaticity:
  Red:   0.5751, 0.3447
  Green: 0.3496, 0.5751
  Blue:  0.1601, 0.1503
  White: 0.3134, 0.3291
Established timings supported:
Standard timings supported:
Detailed mode: Clock 142.000 MHz, 344 mm x 193 mm
               1920 2028 2076 2100 hborder 0
               1080 1090 1100 1126 vborder 0
               -hsync -vsync 
               VertFreq: 60 Hz, HorFreq: 67619 Hz
Manufacturer-specified data, tag 15
ASCII string: AUO
ASCII string: B156HAN06.1 
Checksum: 0xea (valid)
EDID block does NOT conform to EDID 1.4!
        Missing name descriptor
        Missing monitor ranges
(base) rodgomesc in ~ 
```

**Comment by rodgomesc** [comment]
feedback; on every tutorial i folow in web, with semelhand hardware, i always get same kernel panic related to `AppleIntelCLFgraphicsFramebuffer`

**Comment by kirainmoe** [comment]
Can you try this config: https://send.firefox.com/download/b18a291e830a4a8a/#SxYi1-UO_vUzjauxEa3lig

Use ig-platform-id 0x12345678 to boot into system, replace the config and rebuild kext cache (`sudo kextcacahe -i /`)

**Comment by rodgomesc** [comment]
Maybe the problems is `sudo kextcacahe -i /` i only was used this when i change S/L/E files

**Comment by rodgomesc** [comment]
> Can you try this config: https://send.firefox.com/download/b18a291e830a4a8a/#SxYi1-UO_vUzjauxEa3lig
> 
> Use ig-platform-id 0x12345678 to boot into system, replace the config and rebuild kext cache (`sudo kextcacahe -i /`)

no luck with this method, same kernel panic happening.


but i got something, using your repo files, i can bypass kernel panic modifyng `config.plist` > devices > properties and adding this:

```
		<key>Properties</key>
		<dict>
			<key>PciRoot(0x0)/Pci(0x2,0x0)</key>
			<dict>
				<key>AAPL,ig-platform-id</key>
				<data>
				CQClPg==
				</data>
				<key>device-id</key>
				<data>
				PqUACQ==
				</data>
				<key>framebuffer-con1-enable</key>
				<data>
				AQAAAA==
				</data>
				<key>framebuffer-con1-type</key>
				<data>
				AAgAAA==
				</data>
				<key>framebuffer-con2-enable</key>
				<data>
				AQAAAA==
				</data>
				<key>framebuffer-con2-index</key>
				<data>
				/////w==
				</data>
				<key>framebuffer-fbmem</key>
				<data>
				AACQAA==
				</data>
				<key>framebuffer-patch-enable</key>
				<data>
				AQAAAA==
				</data>
				<key>framebuffer-pipecount</key>
				<data>
				AgAAAA==
				</data>
				<key>framebuffer-portcount</key>
				<data>
				AgAAAA==
				</data>
				<key>framebuffer-stolenmem</key>
				<data>
				AAAwAQ==
				</data>
				<key>framebuffer-unifiedmem</key>
				<data>
				AAAAgA==
				</data>
			</dict>
		</dict>
```

[complete config.plist](https://gist.github.com/rodgomesc/20bc6b81f74ac50b70262e63b880e1c4)

after login, 

touchpad not work,
keyboard not work

and only 7mb of video, 

previously i could see **uhd 630 7mb** in the system info now i only see **display monitor 7mb**

**Comment by rodgomesc** [comment]
@kirainmoe  your laptop have `dvmt ` option in bios?

**Comment by kirainmoe** [comment]
no option in BIOS, default DVMT  shown in Windows is 128M.

**Comment by rodgomesc** [comment]
solved with 


´´´
                       <key>PciRoot(0)/Pci(0x02,0)</key>
			<dict>
				<key>disable-external-gpu</key>
				<data>AQAAAA==</data>
				<key>framebuffer-fbmem</key>
				<data>AACQAA==</data>
				<key>framebuffer-patch-enable</key>
				<integer>1</integer>
				<key>framebuffer-stolenmem</key>
				<data>AAAwAQ==</data>
			</dict>
´´´

and clean install of Mojave 10.14.6

**Comment by kirainmoe** [comment]
Actually related to dvmt. It's so strange that these patches exist in my config, but they do not work...Anyway, congrats.

**Comment by rodgomesc** [comment]
Maybe is version of the system, i started a Clean config.plist to

**Comment by rodgomesc** [comment]
@kirainmoe in this line https://github.com/kirainmoe/hasee-tongfang-macos/blob/1da60788d666bdf470da4a7b539daa5277e7b507/config.plist#L574

i dont know why this is working for you but, this needs to be <number> not <data>
