### ISSUE TITLE
z7mkp7z

### ISSUE THREAD

**Issue by neverforevera** [kirainmoe/hasee-tongfang-macos#30]
进系统一两分钟后死机

**Comment by kirainmoe** [comment]
首先检查你的电脑是否更换过配件，如加换过三星/Intel的问题。尽可能多提供信息。

**Comment by woshinibaba1** [comment]
加装过一个Intel760p的固态，不过Mac是装在原有的固态上，760p上装的win，然后每次开机一两分钟死机，鼠标和键盘都动不了，重启几次后能正常用，基本过了几分钟还没死机就能正常用了，还有的时候睡眠唤醒后也会，大概就是这样，电脑是i7-8750h+1050Ti+512g固态那款，自己加了个512gintel760p和8g内存条。

**Comment by kirainmoe** [comment]
如果你没有更换过其他硬件，多半是 Intel 760p 固态硬盘的问题。尝试用 APFS 分区格式重新安装系统。
