### ISSUE TITLE
CT7GK README.md  修改

### ISSUE THREAD

**Issue by Cyanogen-Mod** [kirainmoe/hasee-tongfang-macos#34]
https://github.com/kirainmoe/hasee-tongfang-macos/blob/ct7gk/README.md

我的CT7GS(9750H+1650, 同模具) 出厂无线网卡为9462AC, Intel ARK查询得知走的CNVi协议, 后来购买了走PCIe+USB的Intel AX200安装上正常使用

貌似也支持更换PCIe协议的无线网卡

对接口协议这些不太了解, 不敢贸然提交Pull Request, 请大佬帮忙判断一下

P.S. 请问9代同模具的CT7GS能否按照CT7GK的方法刷入Hackintosh呢

**Comment by kirainmoe** [comment]
经过他人测试已确认同方九代机型支持走 PCIe 协议的网卡，现已去掉 README 中的提示。

CT7GS 与 CT7GK 属于同模具，可以直接使用 CT7GK 的配置文件。
