### ISSUE TITLE
hdmi / type-c

### ISSUE THREAD

**Issue by rodgomesc** [kirainmoe/hasee-tongfang-macos#35]
did you get video working using an adaptor from type-c to hdmi?

like this:

![image](https://user-images.githubusercontent.com/4893591/63066791-41f56b80-bee2-11e9-85df-a574e22ba271.png)

**Comment by kirainmoe** [comment]
If your Type-C port supports USB3.1 gen2 or Thunderbolt, you can use this adapter with some  patches of IGPU. However my Type-C is USB3.1 gen1, so it doesn't support adapter. 

But it seems to be confirmed that some adapters with DisplayLink protocol can work on macOS with DisplayLink driver installed.

**Comment by rodgomesc** [comment]
Have you tested any adapter models that could point me out?

**Comment by kirainmoe** [comment]
See #10.

**Comment by rodgomesc** [comment]
I was folowing this 

https://blog.daliansky.net/Tutorial-Using-Hackintool-to-open-the-correct-pose-of-the-8th-generation-core-display-HDMI-or-DVI-output.html

Make Sense, but o got kernel panic If remove `disable-external-gpu` flag

**Comment by kirainmoe** [comment]
10.14 doesn't support Nvidia egpu.

**Comment by rodgomesc** [comment]
JUA365 USB3.0,  sound Works great but o didn't find a web site to send It to Brazil yet

**Comment by kirainmoe** [comment]
You can try to buy on Amazon, or you can try other adapters of other brands.

**Comment by rodgomesc** [comment]
I Will close this, thanks
