### ISSUE TITLE
z7m-kp7z 进系统一分钟就死机

### ISSUE THREAD

**Issue by 13078417792** [kirainmoe/hasee-tongfang-macos#37]
加装了500g的三星970evo固态和8g的金士顿内存
用的是原装有线网卡，没有换无线网卡
装的是10.14.6的系统。什么功能都正常，就是进系统一分钟（大概）就死机

**Comment by kirainmoe** [comment]
可以确定是三星固态硬盘问题。

**Comment by 13078417792** [comment]
> 可以确定是三星固态硬盘问题。

装在原装硬盘上了也是这样，不过没拔三星硬盘，这样也有关系吗

**Comment by kirainmoe** [comment]
必须要拔掉三星硬盘测试才准确，虽然我没有970Evo，但是类似的PM981和EvoPlus，只要插着就算是数据盘也会死机。另外如果你的970Evo有固件更新，推荐你更新一下再试试。之前群里有人也换了970evo同样的现象。不管怎么样建议先把970evo拔下来看看再说。

**Comment by 13078417792** [comment]
> 可以确定是三星固态硬盘问题，建议拔下970Evo安装在原厂固态试一下，或者把 VirtualSMC相关的Kext换成FakeSMC系列试试，后者我不保证有效。

好的，谢谢，明天试试

**Comment by 13078417792** [comment]
> 必须要拔掉三星硬盘测试才准确，虽然我没有970Evo，但是类似的PM981和EvoPlus，只要插着就算是数据盘也会死机。另外如果你的970Evo有固件更新，推荐你更新一下再试试。之前群里有人也换了970evo同样的现象。不管怎么样建议先把970evo拔下来看看再说。

刚看过了，固件是最新的了

**Comment by 13078417792** [comment]
刚刚把加装的硬盘和内存都拆下来了，依旧是死机
然后使用了镜像自带的EFI就不死机了。。。

**Comment by kirainmoe** [comment]
我回去调查一下。

**Comment by 13078417792** [comment]
![IMG_20190831_160739](https://user-images.githubusercontent.com/22026159/64061197-bc73fa00-cc09-11e9-904e-2d26fc58f677.jpg)
使用主分支的efi提示报错
然后我自己更新了VirtualSMC  LiLu  WhateverGreen
正常进入系统，然后就死机了
