### ISSUE TITLE
Questions about BCM94360CS2

### ISSUE THREAD

**Issue by rodgomesc** [kirainmoe/hasee-tongfang-macos#38]
this wireless card BCM94360CS2, is dual band 2.4 and 5 ghz? it's works natively?

**Comment by rodgomesc** [comment]
the sizes in mm, width and height, is compatible with the slot?

**Comment by kirainmoe** [comment]
bcm94360cs2 supports dual band and 2.4GHz/5GHz, and it works natively because it is taken off from Macbook Air 2013/2014. 

It is not compatible with the M.2. NGFF slot, but you may able to find an adapter which have a M.2 NGFF connector, like [this](https://www.amazon.com/BCM94360CS2-BCM943224PCIEBT2-Card-Adapter-Hackintosh/dp/B01JGERLOS).  The length of this card will be longer about 1.8cm(0.70 in) than the common M.2. NGFF cards, either.

**Comment by kirainmoe** [comment]
Here are three types of wireless card with different length. The common wireless card is 22x30 (like Intel AC9462).

![image.png](https://i.loli.net/2019/09/25/HSBZwXyxdhpAGkq.png)

**Comment by WangChenPeng** [comment]
I'm using BCM94360CS2 and it works perfectly

**Comment by rodgomesc** [comment]
> You may need to take apart your machine and check if there is some space above your wireless card.

i will do this

**Comment by rodgomesc** [comment]
i have a lot of space, and both connectors, M2 and MiniPCI, so i think i will nedd a NGFF conector, for fix the screw in correct place, right?

![image](https://user-images.githubusercontent.com/4893591/66089305-104d6800-e555-11e9-93ec-9e61971eab2f.png)

**Comment by kirainmoe** [comment]
Note that the connector you labelled "Mini PCIE" is actually a NGFF connector.

**Comment by rodgomesc** [comment]
@kirainmoe , but the problem is fix the screw, the size is not compatible

**Comment by kirainmoe** [comment]
No need to fix it, the adaptor will remain a screw hole to match the hole on your motherboard.

**Comment by rodgomesc** [comment]
> No need to fix it, the adaptor will remain a screw hole to match the hole on your motherboard.

but in that image screw are in different positions

![image](https://user-images.githubusercontent.com/4893591/66090241-f0b83e80-e558-11e9-937c-e55451a88161.png)

**Comment by rodgomesc** [comment]
Oh sorrryyyyy,  I was thinking I wouldn't need the adapter anymore

**Comment by kirainmoe** [comment]
Behind the wireless card there is a screw hole on the adapter. You can see it in the Amazon link I posted above.

**Comment by rodgomesc** [comment]
if i buy this adapter, i will put him in m2 slot right? the adapter don't seems do enough size to match with `screew 2` position

![image](https://user-images.githubusercontent.com/4893591/66090492-0417d980-e55a-11e9-9f04-e900b6937d4c.png)

**Comment by rodgomesc** [comment]
i think, this will solve this problem right?

https://www.amazon.com/HUYUN-transforms-BCM94360CSAX-bcm94360cs2-BCM94360CD/dp/B07L3DSTZY/

![image](https://user-images.githubusercontent.com/4893591/66091600-cb2e3380-e55e-11e9-9eea-d9d6f2f74c7d.png)

**Comment by kirainmoe** [comment]
Not in m.2. Take off your intel ac9570ngw, plug in the adapter, lock the screw of H2 in the picture, and plug in the wireless card, then lock the wireless card.
It is preferred to buy a 22x60 adapter.

**Comment by kirainmoe** [comment]
Closing this issue for long time inactivity. Reopen this if you have any other questions.
