### ISSUE TITLE
z7m-kp7gc 睡眠后显示问题

### ISSUE THREAD

**Issue by WangChenPeng** [kirainmoe/hasee-tongfang-macos#39]
使用最新的配置文件后 一切均正常 也运行了那个优化命令,
优化命令中试过开启hihpi也试过关闭 试过自动输入分辨率 也试过默认 也试过说解决比例问题的那个
均出现一个现象 就是睡眠后 屏幕显示比例异常
也出现一个问题 在设置 系统 禁止休眠后 长时间不操作 不知屏幕是自动关闭 还是 屏保了 再次亮屏时也出现了屏幕比例异常的问题

**Comment by kirainmoe** [comment]
出现四分之一屏是 HiDPI 的问题，把分辨率改回 1920x1080 即可。

**Comment by WangChenPeng** [comment]
优化命令可以执行多次吗 后一次的执行覆盖上一次的设置?
我第一次运行的时候 设置的不是1920 1080 之后又设置过1920 1080 还是不好用
哦对 我当时开启hidpi时时选择的 自动注入id的那个选项 跟这个有关系吗

**Comment by kirainmoe** [comment]
我的意思是在系统里设置分辨率为 1920x1080。多次执行以最后一次结果为准。这个问题就是hidpi引起，不论你用什么方式开启都一样。

**Comment by WangChenPeng** [comment]
感谢 重新做了一次后又运行了Kext Utility 这次可以正常睡眠了 不知道之前什么问题. 感谢
