### ISSUE TITLE
请假一个关于分辨率的问题

### ISSUE THREAD

**Issue by WangChenPeng** [kirainmoe/hasee-tongfang-macos#40]
打扰了
我是z7m kp7gc
现在遇到了一个这个问题
就是usb转hdmi转出来以后 分辨率是不对的 和我显示器
最高分辨率也就是1080 也就是 笔记本屏幕的分辨率正常但是外接分辨率不正常
我想问一下 是不是我再次执行那个命令 就是弄分辨率的那个
然后手动设置成我外接屏幕的分辨率 然后外接屏幕的分辨率就正常了呢
这样设置以后 会不会 笔记本屏幕的分辨率又不正常了...
我外接的是带鱼屏.... 用笔记本那种1080很难受...或者说有什么软件能解决呢?
我看了一个easyres好像网上说能解决 但是我下载以后 发现也没我的那个分辨率选项 最大也是到1080
望解答 歇歇

**Comment by kirainmoe** [comment]
下载 RDM 即可调节分辨率：http://avi.alkalay.net/software/RDM/

**Comment by WangChenPeng** [comment]
好的 感谢 另外请问一个问题 appstore 不能二步验证接受验证码 这是什么问题呢?
我记得之前是可以的 今天就不行了 我百度以后 看网上说的 删除一个配置文件 然后删除所有的网络连接
重启之后 重新新建网络连接 然后测试过 还是不能
手机已经接受到二步验证的验证码 但是 电脑上显示遇到未知错误...尴尬
我现在正在重装 看下是否可以解决...

**Comment by kirainmoe** [comment]
首先，确保你电脑的序列号、smuuid 与配置文件自带的不同。如果当前使用的是配置文件原有的序列号，则先使用更新脚本或clover configurator更新。

然后，登出 AppleID和iCloud账号再试一次。

**Comment by WangChenPeng** [comment]
感谢 那可能就是序列号的问题了... 我重装过后 后面再进行随机生成好了...还以为啥问题...我刚进行重装了...尴尬... 感谢 感谢

**Comment by kirainmoe** [comment]
参照 https://discussionschinese.apple.com/thread/140105623

看起来与三码和配置文件是没有关系的。

**Comment by WangChenPeng** [comment]
那登录账号显示 发生未知错误 是否与三码有关? = = 好尴尬 各种错

**Comment by kirainmoe** [comment]
这个我无法判断。事实上，我无法确定更新脚本里的生成三码逻辑是否是正确的，如果你认为这和三码确实有关，可以尝试使用clover configurator 生成。

**Comment by WangChenPeng** [comment]
好像就是苹果抽风 新注册了一个appid就好了 感谢
