### ISSUE TITLE
第三次重启卡panic，进入安全模式安装后，重启依然需要进入安全模式

### ISSUE THREAD

**Issue by ati46** [kirainmoe/hasee-tongfang-macos#42]
**描述问题**  
开机 列出了一堆的kext，出现please go to panic，按照你的教程使用 -x 可以进入安全模式，分辨率什么的都正常， 安装完成后，重新启动依然需要使用 -x。但是安全模式下操作会有限制，能帮忙解决一下这个问题吗？

我的机型：surface book 1，使用的是github上提供的该机型的EFI。
安装的版本：10.15。
错误信息：(https://github.com/ati46/temp/blob/master/fc57e6ec-4499-45ce-bb46-21e49d2d283b.jpg)
镜像：黑过小兵

**Comment by kirainmoe** [comment]
从 log 图上看，是 VoodooGPIO.kext（是VoodooI2C*.kext 的依赖内核拓展）引起的 panic. 

可以删掉 EFI/kexts/Other 下的 VoodooI2C*.kext 再试试。

**Comment by ati46** [comment]
@kirainmoe  谢谢， 删掉这两个文件后，进入系统把这两个VoodooI2C*.kext放入到/System/Library/Extensions/ 目录下，重建缓存， 一切正常，
但是在使用过程中，会出现黑屏重启的现象。

**Comment by kirainmoe** [comment]
请向你所使用的机型的配置文件维护者反馈相关问题。

**Comment by ati46** [comment]
@kirainmoe 好的， 谢谢
