### ISSUE TITLE
ct7gk启动偶尔会卡在进度条进不去系统

### ISSUE THREAD

**Issue by middle2021** [kirainmoe/hasee-tongfang-macos#43]
**描述问题**  
ct7gk启动偶尔会卡在进度条进不去系统

**期望现象**  
希望能成功进入系统

**机器详情**  
- 安装的机型 Z7-CT7GK
- 安装的 macOS 版本 10.14.5
- 安装系统的硬盘 金士顿nvme
- 机器中已安装的其它 还有一块SATA机械盘
- 内存容量和制造商 32G 三星
- 镜像获取渠道 官方渠道
- 是否更换过屏幕或无线网卡等硬件 没有
- 已连接的 USB 设备机器接口

**Comment by kirainmoe** [comment]
请在接下来每次引导的时候使用 `Verbose` 模式（Clover 添加 `-v` 参数）引导系统（方法见[本帖](https://blog.daliansky.net/clover-user-manual.html)），并等待出现卡 log 现象后拍照上传以定位问题。

**Comment by middle2021** [comment]
> 请在接下来每次引导的时候使用 `Verbose` 模式（Clover 添加 `-v` 参数）引导系统（方法见[本帖](https://blog.daliansky.net/clover-user-manual.html)），并等待出现卡 log 现象后拍照上传以定位问题。

好的，了解，谢谢
