### ISSUE TITLE
Please add Turkey seller Monster support...

### ISSUE THREAD

**Issue by Se7Touch** [kirainmoe/hasee-tongfang-macos#44]
Hello, I just found your perfect work when I was going to stop working on hackintosh. First of all, thank you for hard work...

**Describe Your Problem**  
Will Turkey vendor support can be added Monster company? Im using Monster Abra A7 v10.1 - https://www.monsternotebook.com.tr/abra/monster-abra-a7-v10-1/

Im use your master EFI on Catalina and almost all functions are working properly. Only one of my 2 speakers (right) works. Monocolor, mix and flash modes do not work in the keyboard light control program.

**Detail**  
- Monster Abra A7 v10.1
- 10.15.1
- M.2 PCIe NVMe SSD: 256GB XPG SX6000 PRO M.2 SSD PCIe 3.0 x4
- 8GB (1x8GB) DDR4L 1.2V 2666MHz SODIMM
- I didn't change the parts yet. I'm waiting for the compatible wifi card to come from China.
- 1x USB 2.0 - 2x USB 3.1 Gen1 - 1x USB 3.1 Gen1

**Modifications on config**  
Theme and update AppleALC but not work 2 speakers together.

**Attachment (Optional)**  
Use your stock master EFI, not change yet.
Debug Report
[debug_25502.zip](https://github.com/kirainmoe/hasee-tongfang-macos/files/3796297/debug_25502.zip)
: https://www.dropbox.com/s/qzxkmdqgvgmel9l/debug_25502.zip?dl=0

**Comment by kirainmoe** [comment]
Please consider change layout-id to "29"(1D000000) in Device/Properties -> 0x1f, 0x3 (If your sound card is Realtek ALC269vc). If not working, refer to [this table](https://github.com/acidanthera/applealc/wiki/supported-codecs) and try other layout-ids of your device.

Keyboard backlight controller only works on those device with ITE revision 0.02, and the controlling code may be different to your models.

**Comment by Se7Touch** [comment]
Soud problem solved. Can we do something about the keyboard?

**Comment by kirainmoe** [comment]
First check your ITE version, Click Apple->About This Mac->System Report->USB, check the revision of  ITE Device(8291). It should be 0.02; if yours is 0.03, try this repo: https://github.com/rodgomesc/avell-unofficial-control-center

![image.png](https://i.loli.net/2019/11/09/FMwKm5P4NiOBXeW.png)

**Comment by Se7Touch** [comment]
Oh, yes my version id 0.03. I will return to you in relation to this. i go to try...

**Comment by Se7Touch** [comment]
it's really hard to use. I don't think I can. 😅

**Comment by Se7Touch** [comment]
![Ekran Resmi 2019-11-09 19 30 59](https://user-images.githubusercontent.com/16725944/68531880-2d314400-0328-11ea-89c9-83b8605dbb9a.png)

**Comment by kirainmoe** [comment]
Unfortunately, rodgomesc's aucc is the only utility to control the keyboard backlight with ITE version 0.03, as far as I know. And I don't have a device with version 0.03.

If you believe this is a problem of aucc, you may open an issue in rodgomesc's repo.

**Comment by Se7Touch** [comment]
Yeah, I just opened it.

**Comment by Se7Touch** [comment]
i watch this video https://www.youtube.com/watch?v=ai5Y-aoMZWo&feature=youtu.be

its my device in video :)

Thank you for your help. Problem can be close... 👍👏
