### ISSUE TITLE
Can i control my cpu fan ?

### ISSUE THREAD

**Issue by Se7Touch** [kirainmoe/hasee-tongfang-macos#45]
**Describe Your Problem**  
My CPU temperature values is good, empty 40-44, busy 50-55 but my cpu fan always running its a normal ?

**Expected behavior**  
Can i see my fan speed RPM or control it ?

Detail

Monster Abra A7 v10.1
10.15.1
M.2 PCIe NVMe SSD: 256GB XPG SX6000 PRO M.2 SSD PCIe 3.0 x4
8GB (1x8GB) DDR4L 1.2V 2666MHz SODIMM
I didn't change the parts yet. I'm waiting for the compatible wifi card to come from China.
1x USB 2.0 - 2x USB 3.1 Gen1 - 1x USB 3.1 Gen1

![Ekran Resmi 2019-11-09 19 39 49](https://user-images.githubusercontent.com/16725944/68531953-1808e500-0329-11ea-9f4a-dbda7a2b8cfa.png)

**Comment by kirainmoe** [comment]
Currently, there is no fan speed RPM solution for VirtualSMC.kext. It may be possible to use FakeSMC family and implement the DSDT to see the fam RPM, but I haven't tried. If your cpu fans aren't working in an extremely noisy speed, you don't need to be anxious.

**Comment by Se7Touch** [comment]
Okey, thank you so much. So when VirtualSMC.kext brings fan control support, if I do the update, will the controls be activated automatically or will you have to edit them?

**Comment by Se7Touch** [comment]
im enable Cpu/HWPEnable option in config.plist after install HWPEnable.kext S/L/E and copy CPUFriend.kext alternative folder to other folder and reboot pc.

Finally solved my fans running always. And its my appleIntelInfo report...

CPU Ratio Info:
------------------------------------------
Base Clock Frequency (BLCK)............. : 100 MHz
Maximum Efficiency Ratio/Frequency.......:  8 ( 800 MHz)
Maximum non-Turbo Ratio/Frequency........: 22 (2200 MHz)
Maximum Turbo Ratio/Frequency............: 41 (4100 MHz)

IGPU Info:
------------------------------------------
IGPU Current Frequency...................:    0 MHz
IGPU Minimum Frequency...................:  350 MHz
IGPU Maximum Non-Turbo Frequency.........:  350 MHz
IGPU Maximum Turbo Frequency.............: 1100 MHz
IGPU Maximum limit.......................: No Limit

P-State ratio * 100 = Frequency in MHz
------------------------------------------
CPU P-States [ 19 24 (26) ] iGPU P-States [ ]
CPU C3-Cores [ 1 6 7 ]
CPU C7-Cores [ 1 3 5 6 7 8 11 ]
CPU P-States [ (8) 19 24 26 ] iGPU P-States [ ]
CPU C3-Cores [ 1 2 3 6 7 10 ]
CPU C7-Cores [ 0 1 2 3 5 6 7 8 10 11 ]
CPU C7-Cores [ 0 1 2 3 4 5 6 7 8 10 11 ]
CPU P-States [ 8 19 24 (25) 26 ] iGPU P-States [ ]
CPU C3-Cores [ 0 1 2 3 6 7 9 10 ]
CPU C7-Cores [ 0 1 2 3 4 5 6 7 8 9 10 11 ]
CPU P-States [ 8 19 20 (24) 25 26 ] iGPU P-States [ ]
CPU C3-Cores [ 0 1 2 3 5 6 7 9 10 ]
CPU P-States [ 8 19 20 (23) 24 25 26 ] iGPU P-States [ (21) ]
CPU C3-Cores [ 0 1 2 3 5 6 7 9 10 11 ]
CPU P-States [ 8 (9) 19 20 23 24 25 26 ] iGPU P-States [ 21 ]
CPU C3-Cores [ 0 1 2 3 4 5 6 7 9 10 11 ]
bash-3.2#

**Comment by kirainmoe** [comment]
That's great.

**Comment by Se7Touch** [comment]
Thanx for your hard work bro 👏😊
