### ISSUE TITLE
Long time sleep mode...

### ISSUE THREAD

**Issue by Se7Touch** [kirainmoe/hasee-tongfang-macos#46]
I found a problem in my test yesterday. Short sleep mode works perfectly. However, when I tried the long sleep mode, after a while I woke up the black screen. Then I put the device to sleep before going to bed at night. And when I woke up at night I realized that the device had turned itself on. And it was working with a black screen. do you have any idea what caused this problem?

**Comment by kirainmoe** [comment]
Maybe a problem of latest AppleALC. Try to downgrade this kext.

**Comment by Se7Touch** [comment]
Yep. Its work thank you..
