### ISSUE TITLE
WiFi Card does not appear in SystemReport / PCI Devices List.

### ISSUE THREAD

**Issue by Se7Touch** [kirainmoe/hasee-tongfang-macos#47]
Hello,me again :)

I installed my new wifi card (Dell DW1820a CN-096JNT). Its fully working WiFi/Bt

I see my device information in Hackintool/DPCIManager but not see in System Report / PCI device  list... What should I do?
![Screen Shot 2019-11-20 at 18 03 29](https://user-images.githubusercontent.com/16725944/69250141-2cb66a00-0bc0-11ea-9d7f-92135ecd885a.png)
![Screen Shot 2019-11-20 at 18 03 45](https://user-images.githubusercontent.com/16725944/69250157-3213b480-0bc0-11ea-9e4c-d6d514181639.png)
![Screen Shot 2019-11-20 at 18 04 13](https://user-images.githubusercontent.com/16725944/69250165-34760e80-0bc0-11ea-83ca-211e0dfe192d.png)

**Comment by kirainmoe** [comment]
In Hackintool PCIE devices part, right click "BCM4350..." entry and export it as config.plist. then merge the content in the exported config.plist into your config that you are using.

**Comment by Se7Touch** [comment]
I've already added them before. But it still doesn't. That's why I wanted to ask you.
I'm adding my files.


[PCI_devices.zip](https://github.com/kirainmoe/hasee-tongfang-macos/files/3869982/PCI_devices.zip)

![Screen Shot 2019-11-20 at 18 30 21](https://user-images.githubusercontent.com/16725944/69252732-891b8880-0bc4-11ea-8d1b-d29c25c77dd6.png)

**Comment by kirainmoe** [comment]
Once you add these properties, you can see the correct info in `Wi-Fi` tab. It's no matter that it doesn't appears on `PCI` tab.

**Comment by Se7Touch** [comment]
hmm Okey i see informations in Wi-Fi tab no problem. Thanx..
