### ISSUE TITLE
What this ACPI errors ?

### ISSUE THREAD

**Issue by Se7Touch** [kirainmoe/hasee-tongfang-macos#48]
Hello dude, i catch on booting some ACPI errors. Have any idea this errors ?

![IMG_2765](https://user-images.githubusercontent.com/16725944/69502411-18f06800-0f20-11ea-9d56-06a5160f5ebf.jpeg)

**Comment by kirainmoe** [comment]
Tongfang laptops' DSDT method definition is somehow different to the specification. You can ignore these errors since they will not affect anything, only showing error logs during verbose mode.

For fixing it, you may need to modify the DSDT according to the error log, but it isn't necessary.

**Comment by Se7Touch** [comment]
Oh okey. No problem.
