### ISSUE TITLE
Can't change SMBIOS model because after not work USB ports.

### ISSUE THREAD

**Issue by Se7Touch** [kirainmoe/hasee-tongfang-macos#49]
Today I change my SMBIOS model 15.1 to 15.3 but, after changing my USB ports not working. How can I change SMBIOS model correctly?

**Comment by kirainmoe** [comment]
USBInjectAll.kext has no SMBIOS definitions for MacbookPro15,3 and MacbookPro15,4, only 15,1 and 15,2. You may need to modify Info.plist of USBInjectAll.kext or use `Hackintool` to customize USBPorts.kext.

**Comment by Se7Touch** [comment]
Done. Working USB ports after manual add SMBIOS model in USBInjectAll.kext. Thank u...
[USBInjectAll.kext.zip](https://github.com/kirainmoe/hasee-tongfang-macos/files/3886138/USBInjectAll.kext.zip)
