### ISSUE TITLE
You can add my new model in compatibility list.

### ISSUE THREAD

**Issue by Se7Touch** [kirainmoe/hasee-tongfang-macos#50]
Hello i switch Monster Abra A7 v10.1 to Monster Tulpar T7 v19.3 model and installed 10.15.2 with ct7gk fully working. You can add my new model in compatibility list. Thank you too...

CPU: i7 9750H
GPU: GTX 1660Ti

**Comment by kirainmoe** [comment]
Thanks for the feedback. I have added it to compatibility list.
