### ISSUE TITLE
您好，请问使用您提供的优化脚本开启了HIDPI还有办法关闭吗

### ISSUE THREAD

**Issue by HMLDXHZ** [kirainmoe/hasee-tongfang-macos#51]
用了很长一段时间都没开hidpi，今天手痒开了一下感觉超级不习惯 请问有什么办法可以关闭吗qwq

**Comment by kirainmoe** [comment]
把分辨率调回去1920x1080就好了啊

**Comment by HMLDXHZ** [comment]
但我好像感觉调回那个1920x1080以后程序坞变小了 是错觉吗

**Comment by kirainmoe** [comment]
> 如要恢复，删除 /System/Library/Displays/Contents/Resources/Overrides/DisplayVendorID-9e5 即可。如果你是 Catalina 以上系统，你可能需要进入 Recovery 模式下挂载系统分区操作。
```bash
cd /Volumes/"Your System Disk Part"/System/Library/Displays/Contents/Resources/Overrides
rm -rf ./DisplayVendorID-9e5
cp -r ./backup/* ./
```

**Comment by HMLDXHZ** [comment]
谢谢大佬的指导 已经恢复了！多谢
