### ISSUE TITLE
安装过程中出现问题

### ISSUE THREAD

**Issue by y-fy** [kirainmoe/hasee-tongfang-macos#52]
**描述问题**  
安装系统第一次重启出现错误。

![IMG_20200116_160354](https://user-images.githubusercontent.com/56571672/72513684-4acedc80-3888-11ea-8482-c558f4ff9092.jpg)

**机器详情**  
- 安装的机型 [ Z7M-KP5GC]
- 安装的 macOS 版本 [e10.14.6]:  
- 安装系统的硬盘 [东芝xg6]:  
- 机器中已安装的其它 SATA/NVMe 硬盘 （如果有）[机器自带金士顿128g固态盘和日立1t机械硬盘]
- 内存容量和制造商 [e.g. 16GB, 原厂8GB+镁光8GB]:  
- 镜像获取渠道 [e.g. 黑果小兵，Len's DMG]: 
- 已连接的 USB 设备机器接口 [e.g. 安装U盘在左侧接口，USB鼠标在后边的接口]:

**Comment by kirainmoe** [comment]
请检查重启的时候 Clover 是否有多出启动项，如果有进入新启动项进行第二阶段安装。

如果没有，建议安装最新版本 macOS，请严格按照 [视频教程](https://www.bilibili.com/video/av81263778) 中的步骤操作。
