### ISSUE TITLE
最新的KP7GC驱动中缺少VoodooI2C和VoodooI2CHID驱动，导致摄像头无法识别，此外触摸板无法驱动，更换为ApplePS2smarttouchpad驱动后可使用

### ISSUE THREAD

**Issue by clxdbclt** [kirainmoe/hasee-tongfang-macos#53]
**请先阅读以下内容：**  
* 请不要提问有关于“独显如何驱动”、“Intel 无线网卡如何驱动”等问题。
* 请先阅读《安装前须知》：https://dwz.cn/mbmFwWEu ，其中列出了兼容的机型和硬件驱动情况，确保该配置文件适用于你的机型，并且你认为不正常的硬件或功能是可驱动的。
* 请先阅读《安装后的常见问题解答》这篇文章：https://dwz.cn/3sQH81R0 ，其中列出了安装后一些常见问题的解决方案。
* 请先到已关闭的 Issues 区中，寻找一下是否已经有人提过你已经关心的问题；并确定当前未关闭的 Issues 中，没有人提出了和你一样的问题。
* 如果上面的内容都没有解决你的问题，请删除上面的内容并继续。

**描述问题**  
请在这里仔细描述你的问题，包括问题的详细描述、问题出现的阶段等等。

**期望现象**  
请在这里描述你认为正常的期望现象。

**机器详情**  
- 安装的机型 [e.g: Z7-KP7GZ]: 
- 安装的 macOS 版本 [e.g: 10.14.6]:  
- 安装系统的硬盘 [e.g: WD SN750]:  
- 机器中已安装的其它 SATA/NVMe 硬盘 （如果有）[e.g. 三星 PM981]: 
- 内存容量和制造商 [e.g. 16GB, 原厂8GB+镁光8GB]:  
- 镜像获取渠道 [e.g. 黑果小兵，Len's DMG]: 
- 是否更换过屏幕或无线网卡等硬件 [e.g. 更换4K屏幕，更换 bcm94360cs2 无线网卡]: 
- 已连接的 USB 设备机器接口 [e.g. 安装U盘在左侧接口，USB鼠标在右侧接口]: 
- 是否已替换配置文件或进行过其它修改: 

**对配置文件进行的修改**  
请在这里列出你的 `config.plist` 文件的修改、自己添加或删除的 kext 和 ACPI 补丁（如果有）。

**截图（可选）**  
请上传或在这里贴入问题出现时的截图（可以是 Clover 啰嗦模式截图）。你可以使用 `GitHub Attachment` 功能或 [sm.ms](https://sm.ms) 图床。

**附件（可选）**  
如果方便，请上传当前的 CLOVER 文件夹，并且按照这篇文章：https://www.tonymacx86.com/threads/tool-generate-proper-problem-reporting-files.235953/ 中的指示创建问题报告 (Problem Reporting) 文件。

**Comment by kirainmoe** [comment]
1. KP7GC 的触摸板不是 I2C 协议而是 PS2 协议，没有必要添加 VoodooI2C 和 VoodooI2CHID.
2. VoodooI2C 和 VoodooI2CHID 驱动与摄像头无关。
3. KP7GC 的触摸板使用 VoodooPS2Controller 驱动没有手势支持，可自行更换 ApplePS2SmartTouchpad.kext，但 Fn 功能键将不可用，自行选择
