### ISSUE TITLE
ct7gk Keyboard not work after last VoodooPS2Controller update.

### ISSUE THREAD

**Issue by Se7Touch** [kirainmoe/hasee-tongfang-macos#54]
Hello my model ct7gk and my keyboard work with RTC fix but its 2020.1.22 update PS2Controller working keyboard not working after 2020.1.25 PS2Controller, i try back 2020.1.22 PS2Controller...

**Comment by Se7Touch** [comment]
Yes its working after back to 2020.1.22 PS2Controller...

**Comment by kirainmoe** [comment]
Are you using macOS Mojave or macOS Catalina?

**Comment by Se7Touch** [comment]
On Catalina 10.15.2

**Comment by kirainmoe** [comment]
I have updated the VoodooPS2Controller modified by other developers to fix the CapsLock indicator in 1.25's build, but I don't know what he has done. I will take some times to review his code. Before that please keep on the build from 1.22.

**Comment by Se7Touch** [comment]
Okey I keep it thank you. 

对于中国的流行病，我感到非常抱歉。 好好照顾自己.

**Comment by Goshin** [comment]
Well, the commit on Jan. 24 is a workaround for Caps Lock LED Indicator, and it is pretty simple and straightforward, nothing to do with the core. Check it out here. https://github.com/Goshin/VoodooPS2/commit/8929f2807a05e039c7d4d1e08b074043502129c6

You may want to build the VoodooPS2Controller for yourself or try this one bellow. It was built on 10.15.2.

[VoodooPS2Controller.kext.zip](https://github.com/kirainmoe/hasee-tongfang-macos/files/4113371/VoodooPS2Controller.kext.zip)

Btw what do you exactly mean "not working"? Is it stuck on boot, or not responding when typing?

**Comment by Se7Touch** [comment]
Not responding when typing. I try it your zip now.

**Comment by Se7Touch** [comment]
> [VoodooPS2Controller.kext.zip](https://github.com/kirainmoe/hasee-tongfang-macos/files/4113371/VoodooPS2Controller.kext.zip)

Yep, Solved! Fully work this kext with Caps blinking. Thank you. :)

**Comment by Goshin** [comment]
> Not responding when typing. I try it your zip now.

Seems the kext was not loaded correctly. Your log after a fresh boot will be appreciated.

**Comment by Se7Touch** [comment]
Oh okey. I will pay attention to this. Thank you so much for your help. I wish you good work. 😊

**Comment by Goshin** [comment]
> Oh okey. I will pay attention to this. Thank you so much for your help. I wish you good work. 😊

You are welcome.
