### ISSUE TITLE
Mostly working on Intel-TongFang QC7! (Weird sleep issue)

### ISSUE THREAD

**Issue by frickingphil** [kirainmoe/hasee-tongfang-macos#55]
Hi, hopefully this isn't the wrong place for this, but I'd like to thank you for your work on hackintoshing these TongFang laptops: I would like to report that I was able to use a lot of your patches and SSDTs to get nearly everything working on my Eluktronics MAG-15 (aka XMG Fusion 15, Maingear Element, Aftershock Vapor 15 Pro) on Mojave, I may try Catalina soon.

I'd be very open to providing anything you'd need to add this laptop to the compatibility list, like Clover DSDT dumps and such. Just let me know!

**Hardware**
- i7-9750H (UHD 630)
- RTX 2070 Max-Q
- RTL8111 Ethernet
- Intel AX200NGW Wi-Fi (replaced with BCM94360CS2, fully working in macOS)
- ALC269vc (using VoodooHDA as AppleALC kept occasionally failing to load at boot)

**Issues / Untested**
- Odd sleep bug: sleep works perfectly for exactly 2 sleep/wake cycles; after that, instant wake every time sleep is attempted until the laptop is rebooted. (reason: "XHC/HID Activity") I've tried everything, including uninstalling VoodooI2C, VoodooI2CHID, and VoodooPS2 along with disabling all USB ports via USBMap, and the bug still persists, although the wake reason changes to "/HID Activity", with no more mention of XHC. Such a weird bug.
- Fn-key patches don't work on this model; currently using Karabiner-Elements to remap the F-keys in macOS
- STAR BEAT is somewhat broken (patterns work, static/solid colors don't), although I didn't realize this laptop had ITE v0.03. Haven't tested AUCC yet. 
- Haven't tested HDMI out, although I suspect it won't work because I think it's wired to the dGPU
- Haven't tested Thunderbolt, but USB-C works fine

**Working**
- CPU Power Management (including performance mode button adjusting CPU's power limits), system battery consumption at idle is 8-15w. Tested ~6h battery life with web browsing, youtube, light photo editing, and iMessage workload
- UHD 630 & 1080p 144Hz built-in display
- dGPU disable
- Battery monitoring
- I2C-HID Precision Touchpad
- PS/2 Keyboard
- ALC269 via VoodooHDA
- Wi-Fi / BT (via Apple module + m.2 adapter), AirDrop, Handoff, Continuity, Apple Watch Unlock
- Ethernet
- All USB ports
- iCloud Services / iMessage (aside from Find My Mac) via generated serials

Thanks again for your github repository! If you have any ideas for fixing the sleep issue on this laptop, I'd be glad to hear it.

**Comment by kirainmoe** [comment]
1. For the sleep issue, you may need to use `Hackintools` to customize the USBPorts.kext for your laptop to solve the instant wake problem caused by `XHC`. Also apply the [SSDT-GPRW.aml](https://github.com/kirainmoe/hasee-tongfang-macos/blob/master/ACPI/patched/SSDT-GPRW.aml) patch and the `GPRW to XPRW` [ACPI rename](https://github.com/kirainmoe/hasee-tongfang-macos/blob/master/config.plist#L131). 

2. I don't have an idea about the `HID`, but you may try coolstar's kernel patch to disable `AppleIntelLpssI2CController`, see [this](https://github.com/kirainmoe/hasee-tongfang-macos/blob/master/config.plist#L594).

3. > AppleALC kept occasionally failing to load at boot

You may need `FakePCIID.kext` and `FakePCIID_Intel_HDMI._Audio.kext`, then inject the proper `device-id` and `layout-id` device properties.

**Comment by frickingphil** [comment]
Apologies, I forgot to list the ACPI Patches I was using. I've already used USBMap to configure the USB ports properly, and SSDT-GPRW + ACPI Rename are installed as well.

Coincidentally, I just opened Hackintool and noticed that the laptop's Thunderbolt 3 controller also shows up as an XHC device; I'll attempt to disable it and see if that helps, this may be where the phantom XHC wakes are coming from. (now that I think about it, I've dealt with instant wakes in Windows due to the USB-C/TB port.)

As for AppleALC, I went ahead and tried it again, but this time with layout-id 88 instead of 29 (after reading your guide again) and it seems much more reliable. Thanks!

**Comment by frickingphil** [comment]
Hi, just to add more info about this laptop, I had the cover off and noticed that on the motherboard was printed the part number: MBP**GK5C**Q7C-T311, **GK5C**xxT MB v1.1

I think it may be a fair assumption that this "Intel-designed" machine is a variant of the TongFang GK5C.
