### ISSUE TITLE
ct7gk VoodooPS2Controller.kext stuck loading on boot  after remove RTC Fix patch.

### ISSUE THREAD

**Issue by Se7Touch** [kirainmoe/hasee-tongfang-macos#56]
Hello, anybody else having this problem apart from me?

After installing it again, the problem has been fixed.

**Comment by kirainmoe** [comment]
RTC Fix is to fix the hardware problem of 9th gen Tongfang barebone model, you can not remove it if you are using a 9th gen device. It has no relation to the VoodooPS2Controller.kext.

**Comment by Se7Touch** [comment]
Oh my bad! While updating, I accidentally downloaded the master repo. Sorry...
