### ISSUE TITLE
CT7GK出现间歇性断网问题

### ISSUE THREAD

**Issue by obstrux** [kirainmoe/hasee-tongfang-macos#57]
**请先阅读以下内容：**  
* 请不要提问有关于“独显如何驱动”、“Intel 无线网卡如何驱动”等问题。
* 请先阅读《安装前须知》：https://dwz.cn/mbmFwWEu ，其中列出了兼容的机型和硬件驱动情况，确保该配置文件适用于你的机型，并且你认为不正常的硬件或功能是可驱动的。
* 请先阅读《安装后的常见问题解答》这篇文章：https://dwz.cn/3sQH81R0 ，其中列出了安装后一些常见问题的解决方案。
* 请先到已关闭的 Issues 区中，寻找一下是否已经有人提过你已经关心的问题；并确定当前未关闭的 Issues 中，没有人提出了和你一样的问题。
* 如果上面的内容都没有解决你的问题，请删除上面的内容并继续。

**描述问题**  
请在这里仔细描述你的问题，包括问题的详细描述、问题出现的阶段等等。

**期望现象**  
请在这里描述你认为正常的期望现象。

**机器详情**  
- 安装的机型 CT7GK
- 安装的 macOS 版本 10.15.3
- 安装系统的硬盘 金士顿 NVME
- 机器中已安装的其它 SATA/NVMe 硬盘 （如果有）SATA硬盘
- 内存容量和制造商 32G 三星
- 镜像获取渠道 官方镜像
- 是否更换过屏幕或无线网卡等硬件 更换 bcm94360cs2 无线网卡
- 已连接的 USB 设备机器接口 [e.g. 安装U盘在左侧接口，USB鼠标在右侧接口]: 
- 是否已替换配置文件或进行过其它修改: 

**对配置文件进行的修改**  
请在这里列出你的 `config.plist` 文件的修改、自己添加或删除的 kext 和 ACPI 补丁（如果有）。

**截图（可选）**  
请上传或在这里贴入问题出现时的截图（可以是 Clover 啰嗦模式截图）。你可以使用 `GitHub Attachment` 功能或 [sm.ms](https://sm.ms) 图床。

**附件（可选）**  
如果方便，请上传当前的 CLOVER 文件夹，并且按照这篇文章：https://www.tonymacx86.com/threads/tool-generate-proper-problem-reporting-files.235953/ 中的指示创建问题报告 (Problem Reporting) 文件。

**Comment by kirainmoe** [comment]
？

**Comment by kirainmoe** [comment]
具体现象？有线网？无线网？

**Comment by obstrux** [comment]
> 具体现象？有线网？无线网？

有线网和无线网都有，上传时比较容易出现，正常使用也会出现

**Comment by kirainmoe** [comment]
如果有线网和无线网都断，尤其是你换的还是白果拆机卡，建议先排除网络环境问题。

**Comment by obstrux** [comment]
> 具体现象？有线网？无线网？



> 如果有线网和无线网都断，尤其是你换的还是白果拆机卡，建议先排除网络环境问题。

会不会和网卡驱动有关

**Comment by kirainmoe** [comment]
如果你只是有线网卡断，有可能是驱动有问题；但是你无线都断，换的还是白果免驱卡，白果卡 bcm94360cs2 调用的是系统的驱动，所以我觉得跟驱动问题关系不大。

**Comment by obstrux** [comment]
> 如果有线网和无线网都断，尤其是你换的还是白果拆机卡，建议先排除网络环境问题。



> 如果你只是有线网卡断，有可能是驱动有问题；但是你无线都断，换的还是白果免驱卡，白果卡 bcm94360cs2 调用的是系统的驱动，所以我觉得跟驱动问题关系不大。



> 如果你只是有线网卡断，有可能是驱动有问题；但是你无线都断，换的还是白果免驱卡，白果卡 bcm94360cs2 调用的是系统的驱动，所以我觉得跟驱动问题关系不大。

[截图](https://i.imgur.com/RHy7lfw.png)

**Comment by kirainmoe** [comment]
如果你确实怀疑是驱动问题，你可以试试用 OpenCore 引导。

**Comment by obstrux** [comment]
> 如果你确实怀疑是驱动问题，你可以试试用 OpenCore 引导。

好的,感谢
