### ISSUE TITLE
New around here....Just wanted to mention...

### ISSUE THREAD

**Issue by EricHemingway** [kirainmoe/hasee-tongfang-macos#58]
Hi, 

Sorry for putting this in the wrong place, feel free to delete it as desired, but I do not seem to have the  ability to send a message directly to the main contributor (perhaps since I just created this account).

In any case, I just wanted to let you know the GK5CP6X (Clover) version also works for the EVOO (Branded) 15.6" model laptops (Specifically the LP5 model, but I would think LP4 model would also work as only difference is more memory and storage and different dedicated GFX, but same CPU and Intel GPU).

Additional Laptop info can be found here:
EVOO site: www.EVOOProducts.com  (Laptops are THX certified)

(Note: This brand is Exclusively sold thru Walmart.com)

Just thought you might want to add them to the compatibility table (for Catalina).

Thank you for the great work on these configurations!

**Comment by kirainmoe** [comment]
Thanks for the feedback! I will soon add these laptops to compatibility list.
