### ISSUE TITLE
4k屏的配置有误

### ISSUE THREAD

**Issue by LifeToyer** [kirainmoe/hasee-tongfang-macos#59]
您好，非常感谢您将我的提议采纳，单独列出了4k屏版本的配置文件，但经过反复测试，此文件无法驱动4k屏（也已经测试您最新提供的Tongfang Hackintosh Utility程序生成启动文件，均无法启动），细看了一下config.plist，和我上此提供的不一致，我也不知道是哪一项导致的。经测试，修改DeviceProperties为下列配置后是可用的

> 
                <key>PciRoot(0x0)/Pci(0x2,0x0)</key>
                <dict>
                    <key>AAPL,GfxYTile</key>
                    <data>AQAAAA==</data>
                    <key>AAPL,ig-platform-id</key>
                    <data>AACbPg==</data>
                    <key>AAPL,slot-name</key>
                    <string>Built-in</string>
                    <key>device-id</key>
                    <data>mz4AAA==</data>
                    <key>device_type</key>
                    <string>Display Controller</string>
                    <key>dpcd-max-link-rate</key>
                    <data>FAAAAA==</data>
                    <key>enable-cflbkit</key>
                    <data>AQAAAA==</data>
                    <key>enable-dpcd-max-link-rate-fix</key>
                    <data>AQAAAA==</data>
                    <key>enable-hdmi20</key>
                    <data>AQAAAA==</data>
                    <key>enable-lspcon-support</key>
                    <data>AQAAAA==</data>
                    <key>framebuffer-con1-alldata</key>
                    <data>AQUJAAAEAACHAQAA</data>
                    <key>framebuffer-con1-enable</key>
                    <data>AQAAAA==</data>
                    <key>framebuffer-con2-alldata</key>
                    <data>AwQKAAAIAACHAQAA</data>
                    <key>framebuffer-con2-enable</key>
                    <data>AQAAAA==</data>
                    <key>framebuffer-con2-has-lspcon</key>
                    <data>AQAAAA==</data>
                    <key>framebuffer-con2-preferred-lspcon-mode</key>
                    <data>AQAAAA==</data>
                    <key>framebuffer-patch-enable</key>
                    <data>AQAAAA==</data>
                    <key>framebuffer-portcount</key>
                    <data>BAAAAA==</data>
                    <key>framebuffer-unifiedmem</key>
                    <data>AAAAwA==</data>
                    <key>model</key>
                    <string>Intel UHD Graphics 630 (Mobile) </string>
                </dict>

此外，建议将4k屏config.plist中UIScale调整为02，这样在启动阶段就开启hidpi了，苹果图标不会很小很小然后又变大。希望您采纳。

以上配置文件在一下4k屏上测试通过：

> b173zan03.0
b173zan03.1
b173zan03.3(无法开启4k120hz，win10下面能正常4k120hz但到了macos10.15.3下面只能4k60hz，待解决)
b156zan03.0
b156zan05.1(同样无法开启4k120hz，win10下面能正常4k120hz但到了macos10.15.3下面只能4k60hz，待解决)

目前来看可以更换的4k屏比较推荐友达的，基本都可以点亮，亮度可调。

**Comment by kirainmoe** [comment]
好的，可能是遗漏了部分选项，我有时间会检查一下。另外，应该不需要更新特殊的 whatevergreen 吧？

**Comment by LifeToyer** [comment]
> 好的，可能是遗漏了部分选项，我有时间会检查一下。另外，应该不需要更新特殊的 whatevergreen 吧？

不需要特殊的WEG，我就是使用的您提供efi里面的WEG

**Comment by kirainmoe** [comment]
OK

**Comment by kirainmoe** [comment]
请帮忙测试新版本是否还存在此问题：https://gitee.com/kirainmoe/project-starbeat/releases

**Comment by LifeToyer** [comment]
> 请帮忙测试新版本是否还存在此问题：https://gitee.com/kirainmoe/project-starbeat/releases

刚刚更新了你的app，重新在app内选g7-ct7vk，仅勾选4k屏补丁后下载配置文件，依然启动失败，卡苹果进度条。OC我不太会用，以前Clover可以-v看卡在哪儿了

**Comment by LifeToyer** [comment]
![D4B336B0-9210-47B9-AECD-AC3C4E66ACBF](https://user-images.githubusercontent.com/31582326/76307103-23821200-6303-11ea-9e4f-905d1b55b32a.jpeg)

花屏

**Comment by LifeToyer** [comment]
附上我测试可以用的配置文件
[https://github.com/448031516/Simulation_2/blob/master/config_4k_g7ct7vk.plist](url)

**Comment by kirainmoe** [comment]
那这很奇怪……我已经按照你给的配置文件修改了。如果方便的话请试一下不勾选 4K 获取一份配置文件，然后下载 OpenCore Configurator 在 DeviceProperties 里设置上面的参数，看看能否启动。

**Comment by LifeToyer** [comment]
> 那这很奇怪……我已经按照你给的配置文件修改了。如果方便的话请试一下不勾选 4K 获取一份配置文件，然后下载 OpenCore Configurator 在 DeviceProperties 里设置上面的参数，看看能否启动。

改天测试后再反馈你

**Comment by kirainmoe** [comment]
我再次对比了一下上面那份配置，问题可能出在没有删掉 `framebuffer-fbmem` 和 `framebuffer-stolenmem` 上，我现在从主配置文件里删掉了这两个属性，有时间请在测试一次最新版是否仍有问题。

**Comment by LifeToyer** [comment]
> 我再次对比了一下上面那份配置，问题可能出在没有删掉 `framebuffer-fbmem` 和 `framebuffer-stolenmem` 上，我现在从主配置文件里删掉了这两个属性，有时间请在测试一次最新版是否仍有问题。

可以了，app内选g7-ct7vk，仅勾选4k屏补丁后下载配置文件，测试启动成功！另外还有一个问题是启动进度条第一阶段依然是小苹果图标，第二阶段才变大，这个问题把UIScale的值调整为02就可以了。UIScale在NVRAM的4D1EDE05-38C7-4A6A-9CC6-4BCCA8B38C14子项里。

**Comment by kirainmoe** [comment]
OK. UIScale 的问题会在 Tongfang Hackintosh Utility 的下个版本更新里处理
