### ISSUE TITLE
I can't boot on OC boot loader...

### ISSUE THREAD

**Issue by Se7Touch** [kirainmoe/hasee-tongfang-macos#60]
Hello, ready my flash for Catalina with OpenCore.

But I chose my flash on boot and always restarting my pc, can't boot on flash.

Why is this happening?

**Comment by kirainmoe** [comment]
Please make sure you are booting from /EFI/BOOT/bootx64.efi (9KB) but not /EFI/OC/OpenCore.efi.

**Comment by Se7Touch** [comment]
Yes im sure. But i cant :/

**Comment by kirainmoe** [comment]
Are you download the oc-general branch as zip directly?

**Comment by Se7Touch** [comment]
No, im use tool and make efi with my hardware model.

**Comment by kirainmoe** [comment]
Have you seen any error info show in an instant when you boot from the flash..?

**Comment by Se7Touch** [comment]
No, I can't see any errors.  After choosing to start only from flash, the screen goes dark and restart computer.

**Comment by kirainmoe** [comment]
It seems to be strange. Which model did you choose? I will investigate it later.

**Comment by kirainmoe** [comment]
Also tries if you can boot using the config from `gk******-opencore` branch.

**Comment by Se7Touch** [comment]
Okey, im on way. I write here feedback after repeat try.

**Comment by Se7Touch** [comment]
I managed to get to the setup screen. But the interface seems to be in Chinese. I can't understand anything. How can I do Turkish?

**Comment by kirainmoe** [comment]
Set the "prev-lang:kbd" parameter in NVRAM part, see https://khronokernel-2.gitbook.io/opencore-vanilla-desktop-guide/intel-config.plist/coffee-lake . I will change it to English in the future release.

**Comment by Se7Touch** [comment]
Yes, I found it by researching the method you just said and translated it into English. Bootloader startup screen is boring but it works just fine. Is it normal for the start screen to have a completely black background? I found a background image in the files, but it doesn't appear at the beginning.

**Comment by kirainmoe** [comment]
Yes, the default background is black and the background.png isn't loading. So you were finally able to boot OpenCore. Have you found the reason?

**Comment by Se7Touch** [comment]
Yeah, that's my bad. Instead of copying the folders to the /EFI folder, I accidentally copied them to the main directory. 🤦‍♂️
