### ISSUE TITLE
EVOO LP4/LP5 placed across from wrong model number in table

### ISSUE THREAD

**Issue by EricHemingway** [kirainmoe/hasee-tongfang-macos#61]
sorry to bother you again… However, resolution to bug number 58 is actually incorrect on the description page…

The EVOO LP4/LP5 model number is actually  GK5CP6X (note the “P”)...but it was placed in the table in the 8th gen section (across from the incorrect barebones GK5CN6X model), it should be in the 9th gen section (across from the barebones GK5CP6X model).

just thought you would want to know, so that users don’t download the wrong build for their model.

Great work on this project! 

Very much appreciated!

**Comment by kirainmoe** [comment]
Oh, that's my fault. It should be a 9th generation platform.

**Comment by kirainmoe** [comment]
fixed.
