### ISSUE TITLE
黑苹果亮度异常

### ISSUE THREAD

**Issue by qiude-yu** [kirainmoe/hasee-tongfang-macos#62]
从装黑苹果开始电脑会将自身亮度调到最低，需要手机开手电筒才能勉强看到，直到装完系统之后才能按Fn+F12调高，重启之后自己又会将亮度调到最暗。帮帮我，感激不尽！！
电脑型号：神舟Z7M-kp5gc
黑苹果版本：14.6
引导：clover
感激不尽

**Comment by kirainmoe** [comment]
请在显示设置里勾选“自动调节亮度”。

**Comment by qiude-yu** [comment]
黑苹果偏好设置调了没有效果



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Yume Maruyama"<notifications@github.com&gt;; 
发送时间: 2020年3月14日(星期六) 晚上8:28
收件人: "kirainmoe/hasee-tongfang-macos"<hasee-tongfang-macos@noreply.github.com&gt;; 
抄送: "小羽"<949634960@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [kirainmoe/hasee-tongfang-macos] 黑苹果亮度异常 (#62)





 
请在显示设置里勾选“自动调节亮度”。

**Comment by kirainmoe** [comment]
你确定你用的是我的EFI吗？

**Comment by qiude-yu** [comment]
是的，是您发布的。

**Comment by kirainmoe** [comment]
引导clover时左下角有版本提示，请提供你使用的版本。
另外请重新完整替换一次再试试。

**Comment by qiude-yu** [comment]
我用过两个版本都是这样，0126和0208.我用0208装过15.3版本，在安装过程中会调暗，装好之后就不会自动调亮度了。

**Comment by kirainmoe** [comment]
贴一下 sudo nvram -p 的输出。

**Comment by qiude-yu** [comment]
贴了之后问题没有解决

**Comment by kirainmoe** [comment]
？？？
我让你执行命令把命令输出发上来

**Comment by kirainmoe** [comment]
1. 首先执行 sudo nvram -c 清空 nvram
2. 如果 esp 分区存在 nvram.plist，则删除
3. 是否更换过任何硬件
4. 确保自动亮度功能始终开启，ACPI/patched 目录内存在 SSDT-ALS0.aml

**Comment by qiude-yu** [comment]
fakesmc-key-BNum-ui8	%01


security-mode	none


csr-active-config	g%00%00%00


fakesmc-key-$Num-ui8	%01


fakesmc-key-MSFW-ui8	%01%00


fakesmc-key-REV -ch8*	%02%16%0f%00%00h


fakesmc-key-MSPS-ui16	%00%03


fmm-computer-name	macOS%e2%80%99s MacBook Pro


backlight-level	%18$


fakesmc-key-$Adr-ui32	%00%00%03%00


fakesmc-key-EPCI-ui32	%07%b0%f0%00


bluetoothActiveControllerInfo	%aa%0a%87%80%00%00%00%00%90%14|*1N%f4%ca


fakesmc-key-MSAc-ui16	%00%00


SystemAudioVolume	G


fakesmc-key-RMde-char	A


fakesmc-key-BBIN-ui8	%01


flagstate	%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00


specialbootdevice	%02%01%0c%00%d0A%03%0a%00%00%00%00%01%01%06%00%00%17%03%12%0a%00%01%00%ff%ff%00%00%04%01*%00%03%00%00%00%00p%0d%00%00%00%00%00%88R%da%0e%00%00%00%00J%af`%af%f3%96%f2A%99,%c1%86%9d%0a%7f&%02%02%04%03$%00%f7%fct%be|%0b%f3I%91G%01%f4%04.hB%f8=%7f%25%9f<%02L%ba%ea%92_|r%e7%81%7f%ff%04%00


fakesmc-key-BEMB-flag	%01


macOSs-MacBook-Pro:~ macos$

**Comment by qiude-yu** [comment]
原装电脑未动过硬件

**Comment by qiude-yu** [comment]
进黑苹果系统读条的时候亮度是正常的，然后就暗下来（正常是读条一次然后闪一下，在读一次条），暗下来可以手动调亮度，但是重启之后恢复原状

**Comment by kirainmoe** [comment]
按照楼上的步骤执行以排查问题。若仍然不行请打包上传EFI.

**Comment by qiude-yu** [comment]
文件太大上传不了，我怀疑是Fn驱动出的问题，能告诉我怎么删掉它吗，谢谢

**Comment by kirainmoe** [comment]
删除ssdt-fn即可。个人认为与fn无关。

**Comment by qiude-yu** [comment]
删除了还是没用，我也不好意思在向您提问，毕竟就我遇到过这个问题，感谢您对我做出的答复，万分感谢。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Yume Maruyama"<notifications@github.com&gt;; 
发送时间: 2020年3月15日(星期天) 中午1:00
收件人: "kirainmoe/hasee-tongfang-macos"<hasee-tongfang-macos@noreply.github.com&gt;; 
抄送: "小羽"<949634960@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [kirainmoe/hasee-tongfang-macos] 黑苹果亮度异常 (#62)





 
删除ssdt-fn即可。个人认为与fn无关。

**Comment by kirainmoe** [comment]
你清除过NVRAM试过了没有用吗？实在不行Clover引导界面按一次F11.

**Comment by qiude-yu** [comment]
按F11有反应，下次重启又黑了

**Comment by kirainmoe** [comment]
按过F11并且执行过上述操作之后，现在你 sudo nvram -p，应该是没有 fakesmc 等字样的，请自行检查

**Comment by qiude-yu** [comment]
引导按F11就没用fakesmc等字样，开机也正常；重启后不按F11又出现fakesmc

**Comment by qiude-yu** [comment]
就像重启之后，一切设置重置一样

**Comment by kirainmoe** [comment]
你使用的EFI应该有问题，因为从很早开始本仓库的EFI就已经不用FakeSMC了。所以如果你重置之后还出现 fakesmc 的字样，有可能要么你用的 EFI 就有问题，要么又从什么地方读取了一次 NVRAM.  请自行检查黑苹果或ESP磁盘的根目录是否存在 nvram.plist 等等，实在不行建议重装macOS。

**Comment by kirainmoe** [comment]
对了顺带一提为什么我一直在执着于你的 nvram 设置，因为背光亮度是存在 nvram 中的。从你的输出中可以看出 backlight 是一个很小的固定值。

**Comment by qiude-yu** [comment]
[Uploading EFI.zip…]()

**Comment by qiude-yu** [comment]
找不到，没办法了我换回15.3版本吧
