### ISSUE TITLE
Keyboard Issue On Turkish Model Monster Abra A5 v13.4

### ISSUE THREAD

**Issue by ugurrdemirel** [kirainmoe/hasee-tongfang-macos#63]
Hello, I tried different kind of configs using your hackintosh utitly. I successfully installed macOs, but I can't type anything on second install step (I mean create user, restore backup via icloud section). My keyboard and touchpad not working. Which config should I use ? 

[This is the link of my laptop](https://www.monsternotebook.com.tr/abra/monster-abra-a5-v13-4/)

**Comment by kirainmoe** [comment]
That depends on the barebone model of your laptop. Typically GK5CN6X, GJ5CN64, GI5CN54 will work on 8th generation platform. Which config did you use?

**Comment by ugurrdemirel** [comment]
I used both GK5CN6X/GK5CN5X and GI5CN54.

**Comment by ugurrdemirel** [comment]
GK5CN6X/GK5CN5X and GI5CN54 config booting up successfuly but touchpad and keyboard not working.

GJ5CN64 config gives me this output and screen distorted:
```
still waiting for root device
Kext ru.joedm.SMCSuperIO did not stop (return code 0x5)
Kext ru.joedm.SMCSuperIO can't unload - module stop returned 0xdc008017
Kext ru.joedm.SMCSuperIO did not stop (return code 0x5)
Kext ru.joedm.SMCSuperIO can't unload - module stop returned 0xdc008017
```

**Comment by kirainmoe** [comment]
Are you using OC or Clover?

**Comment by ugurrdemirel** [comment]
if I download config from your hackintosh utitly, it gives me oc files so I'm using oc

**Comment by kirainmoe** [comment]
First please ensure that your laptop is a Tongfang barebone based laptop.
Also try a [clover based previous build](https://github.com/kirainmoe/hasee-tongfang-macos/tree/gk5cn6/5x-clover)  and see if it works.
If  it doesn't work, replace `VoodooPS2Controller.kext` with `ApplePS2Controller.kext` and `AppleACPIPS2Nub.kext`. Get these kexs from the following archive: 
[ApplePS2.zip](https://github.com/kirainmoe/hasee-tongfang-macos/files/4354334/ApplePS2.zip)

**Comment by ugurrdemirel** [comment]
I tried clover while waiting your respond and I replaced same thing you said and keyboard is running now. I know how to fix touchpad from previous mojave :) but my screen brightness is not %100 how can I fix it?

**Comment by kirainmoe** [comment]
For the touch pad, if your touch pad is I2C protocol, it should work normally. If you find your touch pad is I2C but it doesn't working, you can download an official release from [alexandred/VoodooI2C](https://github.com/alexandred/VoodooI2C) and replace VoodooI2C.kext and VoodooI2CHID.kext. These 2 kexts in this repo are built for Catalina.

If your touch pad is PS/2 protocol, you may try `ApplePS2SmartTouchpad.kext`. But PS/2 touch pad has limited support, some gesture may not work well.

For the brightness, you can adjust it in System Preference Setting => Display.

**Comment by ugurrdemirel** [comment]
Sorry for the late answer. I successfully installed catalina on my pc with clover. For touchpad, I used VoodooI2C. I'm using asus n10 wifi adapter to use wifi so everythings great, fn functions too. You can add my device to compitable device list, thank you for this repository :)

I use GI5CN54 clover config

**Comment by kirainmoe** [comment]
Device with I2C touchpad is recomended to use the config of GK5CN6X/GK5CN5X.

**Comment by Se7Touch** [comment]
Bu arkadaş sayesinde en kral mac i kullanıyorum saolsun.
