### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by KewlGuyRox** [kirainmoe/hasee-tongfang-macos#64]
Hi,
Thanks for the awesome support on TongFang laptops. I have an OverPowered 17” Gaming Laptop and your OC config works great. I use dual booting macOS Catalina and Win10 and it’s working with the latest revision of OC, where the OC boot menu provides options for both OS. 

Lately I have been trying to triple boot or at least get dual booting with macOS and Linux variant (Linux Mint or Pop!_OS) but the OC boot menu fails to recognize the Linux partition and there is no option to select it except Win10 and macOS . I see the EFI partition gets updated with an Ubuntu folder to point to the Linux partition, just as the Microsoft folder is created for Win10. I can boot to Linux by pressing F7 and bringing up the BIOS boot menu and it can see the Linux partition and after selecting it boots into the Linux environment just fine.

Is there a OC bug with Linux that may be causing this issue?

**Comment by kirainmoe** [comment]
OpenCore does not recognize and show Linux / Grub entries by default, you need to add the Linux (or Grub) entry by yourself.

Add an entry that points to grubx64.efi in `config.plist/Misc/Entries`, like this:

```
PciRoot(0x0)/Pci(0x1F,0x2)/Sata(0x0,0xFFFF,0x0)/HD(1,GPT,5F53561A-E76A-4D5E-9FF6-0484BB9AE499,0x28,0x95FF8)/\EFI\GRUB\GRUBX64.efi
```

The `PciRoot(0x0)/Pci(0x1F,0x2)/Sata(0x0,0xFFFF,0x0)/HD(1,GPT,5F53561A-E76A-4D5E-9FF6-0484BB9AE499,0x28,0x95FF8)/` is the PCI address of your ESP. To find it you may need a DEBUG version of OpenCore, and set `config.plist/Misc/Debug/Target` to `67`. You will find a log file on ESP that contains the address on next boot.

**Comment by KewlGuyRox** [comment]
Is the PCI address unique for each laptop?

**Comment by KewlGuyRox** [comment]
Sounds good. Thank you. You may close this issue.
