### ISSUE TITLE
Latest revision killed sleep

### ISSUE THREAD

**Issue by KewlGuyRox** [kirainmoe/hasee-tongfang-macos#66]
Updated my Overpowered 17” Gaming laptop to the latest OC revision yesterday and now sleep does not work. When I close the lid for it to sleep, it does not sleep, it keeps running somewhat and it just hangs with no display when I open the lid and I have to power off the laptop and power it back on.

**Comment by kirainmoe** [comment]
Sometimes it may take up to 1 minute for laptop to go into the sleep state. If your laptop still can't sleep after a minute,  please provide the output of the following commands:

```shell
pmset -g
pmset -g log | grep "failure"
pmset -g assertions
```

**Comment by KewlGuyRox** [comment]
pmset -g
System-wide power settings:
Currently in use:
 standby              0
 womp                 0
 halfdim              1
 hibernatefile        /var/vm/sleepimage
 proximitywake        0
 powernap             0
 gpuswitch            2
 networkoversleep     0
 disksleep            10
 standbydelayhigh     86400
 sleep                0 (sleep prevented by apsd, identityservicesd, identityservicesd, identityservicesd, identityservicesd, identityservicesd, identityservicesd, identityservicesd, identityservicesd, AddressBookSourceSync, sharingd, mds)
 autopoweroffdelay    28800
 hibernatemode        0
 autopoweroff         1
 ttyskeepawake        1
 displaysleep         2
 tcpkeepalive         1
 highstandbythreshold 50
 standbydelaylow      10800


------------
pmset -g log | grep "failure"
 -- no result..

-------

pmset -g assertions
2020-04-14 19:26:03 -0400 
Assertion status system-wide:
   BackgroundTask                 0
   ApplePushServiceTask           0
   UserIsActive                   1
   PreventUserIdleDisplaySleep    0
   PreventSystemSleep             0
   ExternalMedia                  0
   InternalPreventDisplaySleep    1
   PreventUserIdleSystemSleep     1
   NetworkClientActive            0
Listed by owning process:
   pid 111(hidd): [0x0000000a00098010] 00:00:00 UserIsActive named: "com.apple.iohideventsystem.queue.tickle serviceID:100000348 name:IOHIDEventDriver product:Keyboard eventType:3"  
	Timeout will fire in 120 secs Action=TimeoutActionRelease
   pid 346(sharingd): [0x000000370001817a] 00:01:27 PreventUserIdleSystemSleep named: "Handoff"  
   pid 70(powerd): [0x0000000800108002] 00:01:40 InternalPreventDisplaySleep named: "com.apple.powermanagement.delayDisplayOff"  
	Timeout will fire in 19 secs Action=TimeoutActionTurnOff
Kernel Assertions: 0x4=USB
   id=500  level=255 0x4=USB mod=12/31/69, 7:00 PM description=com.apple.usb.externaldevice.14700000 owner=USB Receiver
Idle sleep preventers: IODisplayWrangler

**Comment by KewlGuyRox** [comment]
I had powered off my laptop yesterday with full battery charge. Tried to power on today and the entire battery had drained. Had to plug it in to boot the laptop.

**Comment by kirainmoe** [comment]
From these logs, I cannot find out the reason of sleep failure, so first we should determine that whether the sleep problem is caused by OC revision:  

- If you just replaced Clover with OC, was the former Clover revision's sleep working fine on the same macOS version?  
- And if you just updated the OC from an older revision, which revision did you use before.
- Did you update the macOS version in these days?

**Comment by kirainmoe** [comment]
Well I have found something strange in your pmset setting. You should have `sleep` >= `displaysleep` (for example: `sleep = displaysleep = 5`) and `disksleep = 0`. 

Use `sudo pmset -a disksleep 0` to set them.

**Comment by KewlGuyRox** [comment]
Ok I will see pmset setting and report back. 

OC 0.5.6 never showed this issue. Everything worked smoothly. In fact even your first OC revision to 0.5.7 done on 4/7 worked fine. Since the 4/8 update I am having issues. Initially I thought it may be my DW1560 WiFi card, so I replaced it with a genuine MacBook WiFi card (BCM943602CS) but that hasn’t solved the sleep issue. 

On a side note, how do I customize the initial OC boot up OS selection screen? I am planning to give this laptop to my son for his full time college work and he wants to customize the icons‘logos on the OS selection screen to his own.

**Comment by kirainmoe** [comment]
On April 8th's update, I fixed the blue screen problem of Windows using OC 0.5.7 by enabling `Boot/Quirks/RebuildAppleMemoryMap` and `Boot/Quirks/SyncRuntimePermission`. I guess this is not the reason. 

Also on that day I updated VoodooI2C kexts to 2.4, added NVMEfix.kext and HibernationFixup.kext. 

I found an issue about sleep of VoodooI2C 2.4 in https://github.com/alexandred/VoodooI2C/issues/284 , however I can't reproduce the problem. So I suspected that the problem is NVMEfix.kext (HibernationFixup.kext is not enabled by default). If the problem still exists, you may try to disable NVMEfix.kext in config.plist, or downgrade the VoodooI2C to v2.3 (If the latter works I can provide a modified version to fix other problems).

About the OC GUI, you can replace `OC/Icons/Background.png` with the image whatever you (or your son) like.

**Comment by KewlGuyRox** [comment]
Thanks. I found the background.png file. Appreciate it.

Regarding the NVMEfix.kext, I will try to disable that and see if that resolves the sleep issue. In the mean time can you please provide the VoodooI2c that may help with this. 

Thank you again for your continued support and help. Your work has made this laptop much more productive.

**Comment by KewlGuyRox** [comment]
So that didn’t fix it. I click on sleep and it turns off the display but I can hear the fans running. Also closing the lid has no effect.  The laptop keeps running.

**Comment by kirainmoe** [comment]
VoodooI2C v2.3 is here, remember to disable VoodooInput.kext in config.plist->Kernel->Add.

[VoodooI2C-v2.3.zip](https://github.com/kirainmoe/hasee-tongfang-macos/files/4490806/VoodooI2C-v2.3.zip)

**Comment by KewlGuyRox** [comment]
I didn’t disable VoodooInput.kext in current config. Should I be doing that before trying VoodooI2C v2.3?

**Comment by KewlGuyRox** [comment]
Same issue. Clicking on sleep just turns off the display and that's it. The keyboard RGB lights are on and the laptop is on as well. The moment I touch a key the display comes back to life.

I think this started to happen after the latest Mac update which was released 2 weeks back.

**Comment by kirainmoe** [comment]
I did investigation on some users but neither of them reported this problem. What is the barebone model of your laptop? The current version should be normal for GK5CN6X, GK5CP6X and etc.

I have no idea about this problem now, but I think you may try a fresh installation of macOS and see if the sleep works.

**Comment by KewlGuyRox** [comment]
It’s an Overpowered 17” Gaming laptop. I am using GK5CN6X OC files through the Tongfang Hackintosh Utility. 

I will try a fresh install and see if that clears up the issue.

**Comment by KewlGuyRox** [comment]
Tried a fresh install. No change. Sleep still fails to work. If I close the lid OR click on sleep option, the display goes off but the keyboard stays lit and the fans are spinning. The moment I touch any key the display turns on.

**Comment by kirainmoe** [comment]
sry, since I didn't have the same laptop as yours, I can not figure out the exact reason. I searched some similar cases these days. The following solutions are what I have found:

- Remove any USB devices and turn off Bluetooth and see if sleep works
- Customize a USB map for your device
- Try to enable / disable Power Nap

**Comment by kirainmoe** [comment]
Please see if the latest release fixed the problem without checking "Load Apple GuC Firmware".

**Comment by kirainmoe** [comment]
I'm closing this issue because it has been inactive for months. If you are still experiencing this problem or having feedbacks, please just reopen this issue.

**Comment by KewlGuyRox** [comment]
Tried the latest release without checking GuC firmware. Same issue. 

Clicking sleep on the apple home button just turns off the display but the keyboard lights and fans are on. The moment I touch the keypad or the mouse the displays turns back on. Tried "fix sleep" on the Tongfang utility but it has no effect.
