### ISSUE TITLE
关于掉声卡的解决方案

### ISSUE THREAD

**Issue by z0brk** [kirainmoe/hasee-tongfang-macos#67]
维护者你好，之前我的机型存在掉声卡的偶发现象，参考过你仓库的EFI声卡注入方式，表示感谢。
目前[AppleALC 1.4.8](https://github.com/acidanthera/AppleALC/releases)已有更新通过延迟`AppleHDAController `的启动，可以解决掉声卡的问题。

> Support startup delay for AppleHDAController via alc-delay property or alcdelay boot-arg (in ms)

1. 启动参数添加：`alcdelay=500 `
2. 设备属性声卡条目下添加：`alcdelay Number 500`

500代表500毫秒，以上方式2选1，亲测声卡稳定。

**Comment by kirainmoe** [comment]
感谢提醒，在最新的 commit 中已经用此方法代替 FakePCIID 和 FakeIntelHDMIAudio 了。
