### ISSUE TITLE
Not work double tap disable touchpad on last update...

### ISSUE THREAD

**Issue by Se7Touch** [kirainmoe/hasee-tongfang-macos#68]
Hi

FN keys works fine, but double tap disable touchpad jest not work.
Im reinstalled FN-Daemon on Utility..
Do you have a guess, buddy?

Ty,

**Comment by Se7Touch** [comment]
I fixed it.

But I had to use the old FN.aml and VoodooPS2Controller.kext files.

[Files.zip](https://github.com/kirainmoe/hasee-tongfang-macos/files/4578119/Files.zip)

**Comment by kirainmoe** [comment]
You may have changed the modifier key (Control and Option) that made TongfangFnDaemon fail to detect the Fn+F5 hotkey.

**Comment by Goshin** [comment]
> You may have changed the modifier key (Control and Option) that made TongfangFnDaemon fail to detect the Fn+F5 hotkey.

Thanks, fixed in https://github.com/Goshin/TongfangKeyboardUtility/commit/6f6fc0ca88e551ab4e203a1f83f2c89cdfda7e0f.

**Comment by kirainmoe** [comment]
Fixed in https://github.com/kirainmoe/hasee-tongfang-macos/commit/4f7d1f7531485124db74b84d17d7fed77642124d .

You can now use the latest config and reinstall the TongfangFnDaemon again to make Fn+F5 work.

**Comment by Se7Touch** [comment]
Yepp, works perfectly with last update! Thanx all :)
