### ISSUE TITLE
关于硬盘无法装载问题

### ISSUE THREAD

**Issue by wangyu6** [kirainmoe/hasee-tongfang-macos#69]
主板型号是N8XXEP6 （由于笔记本维修，换过主板，所以我也不知道这台电脑是什么型号，只能在BIOS里看到主板型号），macos版本是10.15 ，安装的时候，用磁盘工具格式化后无法装载硬盘，重新分区过后也是如此（10.14 也试过，相同的问题）

配置
16g 
intel Pro 7600p 256g + 希捷sata 盘
i7 8750h
GTX1060
非常感谢

**Comment by kirainmoe** [comment]
N8xxEP6 为蓝天模具，不在本项目支持范围内。

根据你描述的问题，请检查你的硬盘分区表是否为 GUID (GPT) 格式，并且存在一个大于 200M 的 ESP 分区。

**Comment by wangyu6** [comment]
非常感谢，确实是esp分区问题
