### ISSUE TITLE
可能存在的外接显示器新姿势

### ISSUE THREAD

**Issue by wangyu6** [kirainmoe/hasee-tongfang-macos#71]
部分神舟战神电脑的外设接口是 HDMIx1 +mini DP x2 然后有一个dp居然是接在核显上的！！
这是不是意味着——只要买一根数据线就可解决外接显示器问题。。。

**Comment by kirainmoe** [comment]
“部分”指的是哪部分？据我所知同方模具的 DP 都接在独显上。

**Comment by wangyu6** [comment]
蓝天模具。。。 （N8EXXEP6)
//没有别的什么的话，可以close了

**Comment by kirainmoe** [comment]
我从来没有说过蓝天的不能外接。只要接口连核显打补丁就可以。
