### ISSUE TITLE
Sleep still not working

### ISSUE THREAD

**Issue by KewlGuyRox** [kirainmoe/hasee-tongfang-macos#74]
Tried the latest release without checking GuC firmware. Same issue.

Clicking sleep on the apple home button just turns off the display but the keyboard lights and fans are on. The moment I touch the keypad or the mouse the displays turns back on. Tried "fix sleep" on the Tongfang utility but it has no effect. Same happens when I close the laptop display.

**Comment by yansigit** [comment]
I can confirm this issue actually happening.
`pmset -g` returning these logs
```
System-wide power settings:
Currently in use:
 standby              0
 womp                 0
 halfdim              1
 hibernatefile        /var/vm/sleepimage
 proximitywake        1
 powernap             0
 gpuswitch            2
 networkoversleep     0
 disksleep            10
 standbydelayhigh     86400
 sleep                0 (sleep prevented by mds, UserEventAgent, mds_stores, UserEventAgent)
 autopoweroffdelay    259200
 hibernatemode        0
 autopoweroff         1
 ttyskeepawake        1
 displaysleep         0
 tcpkeepalive         1
 highstandbythreshold 50
 standbydelaylow      10800
```
---
(Update)
I could fixed with the Tongfang Utility. Ran the sleep fix and updated efi with latest one with it and it's working like charm!
