### ISSUE TITLE
Installing macOS Big Sur Developer Beta

### ISSUE THREAD

**Issue by kirainmoe** [kirainmoe/hasee-tongfang-macos#75]
![Big Sur](https://i.loli.net/2020/06/26/ab3JKdc4t8GHLxV.jpg)

## 提醒：不建议生产力用户更新！建议那些闲的蛋疼的人再去折腾。

由于新系统 kext 注入方式变化，请不要直接从系统设置里OTA更新，也不要使用镜像全新安装。安装方式和往常不同，需要电脑上有另一块硬盘至少有 50G 空间，或者能够将你现在的硬盘拆到另一台电脑上。你需要一个虚拟机环境，将物理硬盘挂载到虚拟机中，在虚拟机完成安装过程，然后从实体机使用 OpenCore 引导。

预览版 OpenCore 下载：[macOS 10.16 Preview EFI](https://github.com/kirainmoe/hasee-tongfang-macos/files/4836385/Tongfang_EFI_BigSur_Preview.zip)

大概安装步骤如下：

1. 在 Windows 下安装 VMware Workstation，VMWare 和 Windows 需要和你准备安装系统的硬盘不在同一个物理硬盘中。
2. 使用 [VMware unlocker](https://github.com/theJaxon/unlocker)  解锁 VMware 的 macOS 支持
3. 在 Windows 下用磁盘工具给一个独立的硬盘划分 60G 以上的可用空间，然后创建虚拟机，系统选择 macOS 10.16，硬盘使用物理硬盘，然后将你准备安装的硬盘挂载进去
4. 下载 macOS 的 cdr 镜像，或者下载 dmg 镜像后在 macOS 下使用磁盘工具转化为 cdr
5. 在虚拟机里安装操作系统，安装完成看到设置界面后关闭虚拟机
6. 把 OpenCore EFI 放进 U 盘里，然后从 U 盘引导新系统
7. 完成设置

注意事项：

1. EFI 里抹掉了三码，请不要用新的 EFI 引导你原先的系统，否则你的 iCloud 等设置会失效
2. 测试 EFI 没有集成各种蓝牙驱动和网络驱动等
3. USB 驱动默认是 KP7GZ 的，请自行替换你使用的机型对应的 SSDT-UIAC.aml
4. 新系统下电池状态无法显示，同时导致触摸板无法设置，但触摸板可以正常使用，其他功能和在 Catalina 下一致

------

## Tips: I don't recommend to install macOS Big Sur now. Please wait for the perfect updating solution in the future.

Ways to inject kernel extensions has changed in macOS Big Sur, we still need to wait acidanthera team to update the OpenCore and Lilu family so that we can directly update from Catalina or install from a base-system image. 

That means you **SHOULD NOT** update the macOS Big Sur from the System Preference Settings now, and creating an installer media is also **UNAVAILABLE**. The only way to install macOS Big Sur on Tongfang Laptops now is to install Big Sur in a VM (the physical disk you want to install macOS Big Sur is mounted to this VM), then boot from the physical disk using OpenCore in the real machine.

For now, you can use the [macOS 10.16 Preview EFI](https://github.com/kirainmoe/hasee-tongfang-macos/files/4836385/Tongfang_EFI_BigSur_Preview.zip) (it is made for GK5CN6X/GK5CN5X, replace the corresponding SSDT-UIAC.aml of your laptop) to boot macOS Big Sur after you installed it in a VM. The installation progress should be link this:

1. Download and install "VMware workstation" in Windows
2. Use [VMware unlocker](https://github.com/theJaxon/unlocker) to add macOS support for VMware. 
3. Create a partition (>= 50G) to install macOS in your disk. The partition should in the disk which is different from the disk that your Windows and VMware are located in.
4. Create a virtual machine of macOS 10.16 system, and mount your physical disk to the VM.
5. Download a macOS 11.0 Big Sur beta install image (.cdr format is preferred, but .dmg is also ok, since it can be converted to .cdr using the DiskUtility in the macOS).
6. Install the macOS Big Sur system in the VM. After seeing the greeting page, shutdown the VM.
7. Copy the preview EFI to your flash disk, then boot OpenCore from the flash.
8. Done.

**Comment by Se7Touch** [comment]
Thanx for inf bro, waiting...

**Comment by kirainmoe** [comment]
http://bbs.pcbeta.com/viewthread-1862232-1-2.html

**Comment by kirainmoe** [comment]
macOS Big Sur Beta2 is now ready for OTA updating and fresh installing. Closing.
