### ISSUE TITLE
Airplane Mode, Off Topic

### ISSUE THREAD

**Issue by rodgomesc** [kirainmoe/hasee-tongfang-macos#76]
heelo, this is not directly related to hackintosh.

but as the people involved in this project have low level hardware knowledge, I decided to ask for help, recently my tongfang-gi5cn5e, damaged the keyboard, and at that moment my system (ubuntu) was in air plane mode, since then I have not been able to reactivate my wifi card on windows or linux, can anyone tell me if there is any way to disable airplane mode without the hardware switcher shortcuts on the keyboard? (was fn + f4), I tried to reset the bios, but without success. I consider myself an advanced user if I have a solution even though I find it difficult to be implemented, I'm listening

**Comment by Goshin** [comment]
Fn hotkeys are sent via the WMI device. In the WMI driver of Linux, the WMI event of WiFi toggling is usually implemented by sending a key event with `KEY_WLAN` keycode (or `KEY_RFKILL` for airplane mode). So you may try sending a `KEY_WLAN` event to spoof a WiFi hotkey press.

*Implementation of WiFi toggling might differ in different OSes, so it might not work if you disabled WiFi in Windows.

**Comment by rodgomesc** [comment]
thank you for the feedback, i will try our suggestions
