### ISSUE TITLE
orig DSDT

### ISSUE THREAD

**Issue by corint1** [kirainmoe/hasee-tongfang-macos#77]
upload original DSDT please ...thank you

**Comment by kirainmoe** [comment]
Different machines have different DSDTs, and it is not suitable for a public EFI to have any DSDT file. I have already used SSDT and ACPI renames to patch the DSDT and they should be finely working. Why you need the original DSDT?

**Comment by corint1** [comment]
of course, each system has its own particularities and of course each has a different DSDT ... but I want your original DSDT to deduce how you applied those patches ... I tried but without a source it is not possible ... that's why , please, put and the original, unmodified DSDT ... there are many variables or methods or devices that I can't find in my system .... and I want by analogy to try to reproduce on my system what you did with yours ... thank you

**Comment by kirainmoe** [comment]
[DSDT.zip](https://github.com/kirainmoe/hasee-tongfang-macos/files/5010580/DSDT.zip)
