### ISSUE TITLE
9750H cpu跑不满 是默认节能模式了么 

### ISSUE THREAD

**Issue by Pursue-LLL** [kirainmoe/hasee-tongfang-macos#78]
cpu friend 不支持9代u么

**Comment by kirainmoe** [comment]
默认的 CPUFriend 配置模式是 "Max Power Saving" 模式，如果跑不满，可以选择不加载 CPUFriends，或使用 https://github.com/stevezhengshiqi/one-key-cpufriend/blob/master/README_CN.md 中提供的方法自行定制 CPUFriend.kext
