### ISSUE TITLE
What kind of USB Display Adapter to extend the screen

### ISSUE THREAD

**Issue by PudyJapan** [kirainmoe/hasee-tongfang-macos#83]
Hi,

I have Recoil III with 8th gen 6 core processor and everything works very well.

I can see that I can't use HDMI or DP since it's attached to dGPU. What kind of USB display adapter can I use to extend the screen, are there recommendation for compatibility?

Thanks for advance.

**Comment by kirainmoe** [comment]
USB adapter supports “DisplayLink” can be used to extend the screen. For example, [j5create](https://j5create.com/) adapters are known to work, although I don’t know whether these products sell in your region or not.

**Comment by PudyJapan** [comment]
Thank you!

**Comment by PudyJapan** [comment]
@kirainmoe 
I am sorry to reopen the issue. But would a usb type c to HDMI or DP adapter that would normally work with a mac work with tongfang based hackintosh?
Also if I got a monitor with usb type c input would I be able to connect it directly with a usb type c cable?

**Comment by kirainmoe** [comment]
> would a usb type c to HDMI or DP adapter that would normally work with a mac work with tongfang based hackintosh?

Typically not, unless your adapter supports DisplayLink or some other protocols that support convert HDMI/DP signal to USB signal.

>  if I got a monitor with usb type c input would I be able to connect it directly with a usb type c cable?

No.

**Comment by PudyJapan** [comment]
Thank you very much for the quick reply. I really appreciate it.

**Comment by drungrin** [comment]
I use a dell D6000, based on DisplayLink, used to drive 3 monitors, 1x4k and 2x full hd. Now replaced with a 32:9 5120x1440. All worked great.

> I am sorry to reopen the issue. But would a usb type c to HDMI or DP adapter that would normally work with a mac work with tongfang based hackintosh?

Tried USB -> DisplayPort and USB->HDMI, the Tongfang notebooks USB-C ports doesn't support "mode change" so they don't work, even on Windows. The Mac USB-C ports does support "mode change".

Leaving this comment to help others that reach this issue.

No need to reopen the issue.
