### ISSUE TITLE
Tongfang Hackintosh Utility

### ISSUE THREAD

**Issue by 7workday** [kirainmoe/hasee-tongfang-macos#85]
<img width="900" alt="QQ20200925-0" src="https://user-images.githubusercontent.com/56962992/94281492-4911f880-ff81-11ea-898f-1b6d0a44f8c5.png">
一直卡在正在下载驱动拓展包，重启几次软件都无效

**Comment by kirainmoe** [comment]
执行以下命令：
```bash
rm -rf ~/.tfu
```
然后重试下载。如果问题依旧，请检查你是否能正常访问 `cdn.jsdelivr.net`

**Comment by 7workday** [comment]
大佬，可以了，感谢🙏
