### ISSUE TITLE
[OC] First boot loader errors

### ISSUE THREAD

**Issue by rlindsberg** [kirainmoe/hasee-tongfang-macos#86]
![94182290-109aed80-fea1-11ea-8ae0-854a0944c173](https://user-images.githubusercontent.com/2918707/95390620-f8da5500-08f5-11eb-9dbb-a6e99882024b.PNG)

适用于: macOS Catalina 10.15.4， 10.15.6， 10.15.7
影响: 未知
描述: 升级到10.15.4以后在Opencore引导的-v日志之前会出现上面的错误代码。10.15.3没有错误代码
硬件: HM370，8750H，UHD 630

**Comment by kirainmoe** [comment]
这是新版 OC/Clover 的正常日志输出，不是错误。

**Comment by rlindsberg** [comment]
这样啊。。
但是你看上面写的Err，就是Error，然后failure就是失败的意思
然后倒数第二行，打开prelink内核错误

**Comment by kirainmoe** [comment]
正常现象，没有任何影响。
