### ISSUE TITLE
Trackpad not working as intended

### ISSUE THREAD

**Issue by marcustut** [kirainmoe/hasee-tongfang-macos#87]
Tongfang GK5CP5V here and I'm on Big Sur.

Used tongfang-hackintosh-utility and it worked fine booting into the system with almost everything working except the trackpad, it is usable but click is not working neither tap-to-click as well.

Tried both Catalina and Big Sur, both not working

**Comment by kirainmoe** [comment]
Set it in System Preference Setting.

**Comment by marcustut** [comment]
Oh... didn't realise I need to enable tap-to-click in the system preferences, thanks for the quick reply. Your work is awesome 👍🏼

**Comment by marcustut** [comment]
Btw, the physical click buttons still doesn't work, is that a bug with current issue that I can't fix from my side?

Tap-to-click works now in System Preferences but since physical buttons not working I'm unable to highlight text with the trackpad

**Comment by kirainmoe** [comment]
Tested and confirmed that physical buttons are working.

Please ensure that you have checked "Look up & data detectors" and set the triggering method as "Force click with one finger". Statements of the option may be different in your language.

![Screen Shot 2020-12-07 at 17.37.42.png](https://i.loli.net/2020/12/07/ealftMgOJ52nThb.png)

**Comment by marcustut** [comment]
I tried with your settings but, it still doesn't work, is there anyway I can provide a log for you?

**Comment by kirainmoe** [comment]
provide your setting screenshot

**Comment by marcustut** [comment]
![image](https://user-images.githubusercontent.com/59773847/101344283-32ace500-38c0-11eb-8786-cd50fed418da.png)

Here's the screenshot
