### ISSUE TITLE
z7 kp7gz macos big sur 进入系统卡死了，要强制关机后在开机才能进入必现的bug请问能帮忙修复吗？谢谢

### ISSUE THREAD

**Issue by codewindy** [kirainmoe/hasee-tongfang-macos#89]
* 以前一直用的clover引导，后面更新到opencore就会出现这个问题，我的电脑机型和硬件配置几乎跟你的一样
* 如图
* ![image.png](https://i.loli.net/2020/12/24/a42ET3oilSqruDy.png)
* ![image.png](https://i.loli.net/2020/12/24/jWoyx5kSJHKiE6l.png)
* ![image.png](https://i.loli.net/2020/12/24/OaEsiqfxKnHAm42.png)

**Comment by codewindy** [comment]
* 就是说 每次开机都卡死在这个进度条，然后半天一直不动，需要手动强制关机后在重新按开机按钮才能进入，第二次进入就不会卡死了

**Comment by kirainmoe** [comment]
每次开机都会？

**Comment by kirainmoe** [comment]
如果每次开机都会，试着在配置文件的 boot-args 加一下 -v 或者开机的时候按一下 Windows+V，观察一下每次不动的时候卡在什么地方。

**Comment by codewindy** [comment]
* 拍了一个视频，可能是我一开始先进入win10后面重启切换系统到macos之后就会这样经常出现，如果一开机就进入macos就不会，但是一卡死我就怕，以后不更新了改一次好麻烦浪费时间
* https://v.douyin.com/JgFsN16/ 视频是这个，**不过现在重启后正常了**，可能等会回复不了要去上班了昨晚版本上线加班在家才开机

**Comment by codewindy** [comment]
好的，谢谢，我先记下了，周末抽空再试试上班去了
