### ISSUE TITLE
Monster abra a5 v15.8 (GK5MRFV) Succesfull install

### ISSUE THREAD

**Issue by sadikbircan** [kirainmoe/hasee-tongfang-macos#90]
I installed mac os big sur on monster abra a5 v15.8(GK5MRFV barebone) with Monster Tulpar T7 v20.1(9th gen) config. Everything fine with first attemp, doesn't need any additional kext or settings for boot and install. 

Hardware:
Monster Abra A5 v15.8 
-CPU: İntel i7 10750h 
-GPU: İntel UHD Graphics, Nvidia GTX 1650Ti(Not working)
-RAM: 16 GB DDR4 @ 2933 MHz
-Monitor: 1080p@120Hz
-Sound: Realtek ALC274. (Works with VodooHDA only)
-Networks: Intel Wifi 6 AX201 / Realtek RTL8168/8111 PCI-E Gigabit Ethernet
-Storage : SAMSUNG MZVLQ256HAJD-00000  (256 GB, PCI-E 3.0 x4) /KINGSTON SV300S37A240G  (240 GB, SATA-III) 
SATA disk used for install, didn't try nvme support

**Comment by kirainmoe** [comment]
This config is made for 8/9th gen laptops which have Realtek ALC269 sound card, but 10th gen laptops have another model of sound card (possibly, ALC256?).

**Comment by sadikbircan** [comment]
I checked it's ALC274

**Comment by kirainmoe** [comment]
Well, since I have no 10th gen laptop, I cannot fix it with my attempt. If it is convenient for you, please perform the following operations to provide me an sound card codec file:

1. boot into a Linux system (e.g. Ubuntu or any other distro). You don't need to install it but just need a Live CD image.

2.  copy `/proc/asound/card*/codec*` (* represents any character) to your desktop. These are the codec files of all sound cards.

3. pack these codec files and upload them as attachment.

Or you can also try to make an AppleALC layout file for your sound card by yourself.

**Comment by sadikbircan** [comment]
Thanks, i will do it when i have time. I found the layout id of alc274 and tried alcid bootarg and some patched alc kexts that didn't work. Only VodooHDA kext looks like working but no sound still.

**Comment by kirainmoe** [comment]
I have found a dump codec of ALC274 on tonymacx86. I will try to make an AppleALC layout.

**Comment by kirainmoe** [comment]
Remain AppleHDA.kext not patched, uninstall VoodooHDA, and try this:  
[AppleALC.kext.zip](https://github.com/kirainmoe/hasee-tongfang-macos/files/5860532/AppleALC.kext.zip)

In config.plist:

1. change `DeviceProperties -> PciRoot(0x0)/Pci(0x1f,0x3) -> layout-id` from `1D000000` to `23000000`
2. append ` -igfxnohdmi` to `NVRAM -> 7C436110-AB2A-4BBB-A880-FE41995C9F82 -> boot-args`

Then reboot to see if the sound card works, and tell me the result - Chances are that there may be some mistakes in my porting process so the sound is still broken.

**Comment by sadikbircan** [comment]
I tried that and didn't work. I will download an linux system try to dump sound card codec files.

**Comment by kirainmoe** [comment]
Also try to remove `DeviceProperties -> PciRoot(0x0)/Pci(0x1f,0x3) -> device-id` or change it to `C89D0000`

**Comment by sadikbircan** [comment]
Mac OS wont booting stuck at apple logo after removing device id changing it to C89D0000 is no sound still.

**Comment by sadikbircan** [comment]
[VoodooHDA.kext.zip](https://github.com/kirainmoe/hasee-tongfang-macos/files/5862674/VoodooHDA.kext.zip)
Sound fixed with VodooHDA kext I found on tonymacx86. Mic and Speakers working fine now.

**Comment by kirainmoe** [comment]
It has been a long time and someone finally have made a custom layout for ALC274. Now it should work with `alcid=28` boot argument and latest AppleALC version. Remember to delete any parameters in `DeviceProperties -> PciRoot(0x0)/Pci(0x1f,0x3)`. 

Please try this solution and see whether it works, if convenient.
