### ISSUE TITLE
亮度调节问题

### ISSUE THREAD

**Issue by HydroCarbon** [kirainmoe/hasee-tongfang-macos#93]
设备是 KP7D2，安装的是 BigSur 11.2。其他功能看起来都是正常的，但是亮度调节没有作用。
显示器里面有亮度调节的滑动条。
电脑没有更换过屏幕，是原装的屏幕。

**Comment by kirainmoe** [comment]
请确认此问题是近期发生或一直存在。

如果是近期发生，请尝试手动降级 WhateverGreen 到 1.4.5 版本：https://github.com/acidanthera/WhateverGreen/releases/tag/1.4.5

**Comment by HydroCarbon** [comment]
我是今天才装的，不知道以前是不是这样。。。。。之前是 Catalina 使用的 Clover 自己配置的。
我稍后试试降级 WhateverGreen。
谢谢你。

**Comment by HydroCarbon** [comment]
@kirainmoe 试了一下，降级到 1.4.5 可以了，亮度调节正常了。
谢谢您的付出。
