### ISSUE TITLE
Battery Stopped Working in Big Sur OverPowered OP-LP3 Model GK7CN6S

### ISSUE THREAD

**Issue by osxfr33k** [kirainmoe/hasee-tongfang-macos#94]
I am having a huge amount of ACPI errors that was not present in Catalina.   I have uploaded my Config, Kernel log and Native DSDT, files are small size.  I also notice the LCD very slightly flickers this was not an issue in Catalina.  The EFI was downloaded using the manager you provide and I just updated the kexts today.  I noticed less ACPI errors with ACPIBatteryManager.kext and more with SMCBatteryManager.kext but neither kext enables battery in BigSur.

[Config Kernel Log and NAtive DSDT.zip](https://github.com/kirainmoe/hasee-tongfang-macos/files/6043850/Config.Kernel.Log.and.NAtive.DSDT.zip)

**Comment by kirainmoe** [comment]
It seems that the DSDT has been patched correctly, and the config is also correct. However, the kernel log shows that SMCBatteryManager.kext may not be correctly loaded.

You may need to provide your macOS version and full EFI/OC folder for further investigation. On the other hand, please ensure that you are booting with the latest EFI. You can use the command `nvram -p | grep efi-version` to know about it.

**Comment by osxfr33k** [comment]
efi-version 21.2.5%00.  I have to apologize it looks like I did not have your "SSDT-EC-USBX.aml" in ACPI but rather the one I generated using Hackentool to generate my USBPorts.kext and SSDT-EC-USBX and there was no EC code in the SSDT not sure why hackentool does not put the code there when it generates a filename SSDT-EC-USBX.aml, it makes you believe from the filename EC code is included?   So it looks like this was an Embedded Controller issue, battery is now working.  In IOregistry should I see EC EC0 and HECI and under EC0 I see AppleACPIE we want it under EC0 and not EC correct?  But should I have HECI, EC0 and EC in IORegistry?   I am looking for AppleBusPowerController under EC, I cannot find it.


![Screen Shot 2021-02-25 at 9 19 29 PM](https://user-images.githubusercontent.com/9640174/109251290-cea80780-77b0-11eb-9175-061a60b44c5b.png)


![Screen Shot 2021-02-25 at 9 25 18 PM](https://user-images.githubusercontent.com/9640174/109251295-d10a6180-77b0-11eb-8d30-5679f022009e.png)

?  See the two screenshots I have uploaded.

**Comment by kirainmoe** [comment]
You will see EC0 and EC regions in IORegistryExplorer and won't see H_EC region. H_EC is often for Lenovo laptops. HECI region is related to IGPU and it is renamed to IMEI  by WhateverGreen so you won't see it in IORegistryExplorer either.

EC is just a fake ACPI region that does nothing, but this ACPI region is required for macOS 10.15+. EC0 is the real ACPI region of Embedded Controller of Tongfang laptops.

**Comment by osxfr33k** [comment]
I see thanks a lot, do you know why we don't have AppleBusPowerController in IORegistry, is this obsolete in MacOS Big Sur?

**Comment by kirainmoe** [comment]
I don't know where the AppleBusPowerController should be in IORegistryExplorer. This kernel extension does load if SSDT-EC-USBX.aml is present. You can run `kextstat | grep AppleBusPowerController` in terminal and it will give an output shows that AppleBusPowerController is loaded.

**Comment by osxfr33k** [comment]
Ok thanks for all the replies and for your patience this was extremely helpful I can close the topic now its resolved thanks again!
