### ISSUE TITLE
Cursor often jumps to lower-left corner of screen when using trackpad in MacOSX Bug Sur on EVOO LP5

### ISSUE THREAD

**Issue by EricHemingway** [kirainmoe/hasee-tongfang-macos#96]
I am fairly certain this is NOT a  hardware issue as it does not occur in Windows 10, only in MacOSX:

Occasionally when using the trackpad on an EVOO LP5 the cursor will jump to the lower left corner of the screen.  It happens fairly regularly with trackpad use (just tapping the trackpad and moving the cursor (with tap to click off) for less than a minute will almost always cause the cursor to jump to the lower left within less than a minute.   Using an external mouse this does not seem to occur.  Using the trackpad with windows does not seem to have an issue either.

It seems that only the combo of the Trackpad and MacOSX (Big Sur... but I am fairly certain I saw this also in Catalina at one point) seems to make this happen.

Any suggestions for things to try or workarounds?

**Comment by kirainmoe** [comment]
Try to upgrade / downgrade VoodooI2C and its satellite kexts: https://github.com/VoodooI2C/VoodooI2C/releases

If this solution doesn't works, try to make a fresh install of macOS or open an issue at VoodooI2C repo to report the problem.

**Comment by EricHemingway** [comment]
Thanks, I will give that a try!
